### ISSUE TITLE
lodash library in new release

### ISSUE THREAD

**Issue by lovery** [valor-software/ng2-tree#103]
@rychkog I'm getting this error for every import of lodash:
```Module '"/home/lovery/magic-workspace/js/node_modules/@types/lodash/get/index"' resolves to a non-module entity and cannot be imported using this construct.```
If I change the import from `import * as _get from 'lodash/get';` to `import * as _ from 'lodash';` the error disappear. Do you have any I idea what is this happening?

**Comment by rychkog** [comment]
@lovery How can I reproduce this? I am not able on my setup... I've generated a new project via AngularCLI with latest ng2-tree (alpha.6) from npm in a package.json and it works ...
