### ISSUE TITLE
Not loading using systemjs.config.js

### ISSUE THREAD

**Issue by rezarr** [valor-software/ng2-tree#104]
I just installed ng2_tree:       "ng2-tree": "^2.0.0-alpha.6",

I have added ng2_tree to my system.config.js
                'ng2-tree': 'node_modules/ng2-tree',
                'moment': 'node_modules/moment/moment.js',
                'lodash': 'node_modules/lodash/index.js',
            },
            packages: {
                app: {
                    main: './main.js'
                }, 'ag-grid': {
                    main: 'main.js'
                },'ng2-tree': {
                    main: 'index.js',
                    defaultExtension: 'js'
                }

and I can not load the ng2-tree module. I get the following error:

![screen shot 2017-06-22 at 3 06 01 pm](https://user-images.githubusercontent.com/4840697/27458124-59d691e2-575c-11e7-918a-e00e5f50f57a.png)

Is the reason an issue with my systemjs.config.js file?

**Comment by rychkog** [comment]
@rezarr Yes, thanks - already looking at this. Will try to release new version today
