### ISSUE TITLE
I want each node to be a angular4 component

### ISSUE THREAD

**Issue by greenpdx** [valor-software/ng2-tree#107]
I have a usage that the value of each node it not a string, but an object. and I want to use a angular component to display that object. 

In tree-internal.component.ts

       <div class="node-value"
          *ngIf="!shouldShowInputForTreeValue()"
          [class.node-selected]="isSelected"
          (click)="onNodeSelected($event)">
            <div *ngIf="tree.nodeTemplate" class="node-template" [innerHTML]="tree.nodeTemplate | safeHtml"></div>
            <span class="node-name" [innerHTML]="tree.value | safeHtml"></span>
            <span class="loading-children" *ngIf="tree.childrenAreBeingLoaded()"></span>
        </div>

just replace the inner div and span with the angular component passing in "tree" object. This would allow the template to display everything.

**Comment by rychkog** [comment]
@greenpdx PRs are welcomed

**Comment by jcimoch** [comment]
Are you planning to add this functionality in a short time?

**Comment by rychkog** [comment]
@jcimoch This feature belongs to "Nice to have" category. I suppose it will be implemented eventually but it is hard to say when. Though if you want to help and develop this on your own I would help you.

**Comment by ajitraju** [comment]
@rychkog did you implement this feature ? if not can you help in doing this feature.

**Comment by ajitraju** [comment]
@rychkog did you implement this feature ? if not can you help in doing this feature. we are struggling to achieve this feature. we want node should accept angular 2/4 components.
