### ISSUE TITLE
Build Issues with Angular 4

### ISSUE THREAD

**Issue by RedLion73** [valor-software/ng2-tree#108]
Followed all instructions.  VS Code seems to recognize all imports and paths. 

Getting 20 or so messages similar to this upon building.  Do the instructions omit something related to Angular 4?

ERROR in ./~/ng2-tree/src/tree.js
Module not found: Error: Can't resolve 'lodash-es/isArray' in 'c:\<confidential_project_path>\node_modules\ng2-tree\src'
 @ ./~/ng2-tree/src/tree.js 15:16-44
 @ ./~/ng2-tree/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by rychkog** [comment]
@RedLion73 That's true - working on the fix... It is related to the fix introduced recently for the SystemJS users

**Comment by rychkog** [comment]
@RedLion73 as a temporal workaround you can do:

```
npm i -S lodash-es
```

**Comment by RedLion73** [comment]
Closed why?  Resolved?

**Comment by rychkog** [comment]
@RedLion73 Yes, in alpha 8
