### ISSUE TITLE
NodeRemovedEvent: positionInParent: -1 instead of former position in children-array

### ISSUE THREAD

**Issue by motabass** [valor-software/ng2-tree#111]

**Comment by rychkog** [comment]
@motabass Thanks, will look into it today

**Comment by motabass** [comment]
@rychkog Hi and thanks for the quick reply. I also looked into the Issue inside your src and found that when i do
`public fireNodeRemoved(tree: Tree): void {
    this.nodeRemoved$.next(new NodeRemovedEvent(Object.assign(tree)));
  }`
instead of 
`public fireNodeRemoved(tree: Tree): void {
    this.nodeRemoved$.next(new NodeRemovedEvent(tree));
  }`
it seems to work the right way and gves me former index.

Somehow the **Tree** object changes after calling **next()**

**Comment by rychkog** [comment]
@motabass merged and available in the new version
