### ISSUE TITLE
Error in ionic 2 application

### ISSUE THREAD

**Issue by JaviRpo** [valor-software/ng2-tree#121]
How can use this in ionic 2 app.

I follow all steps, but I have this error

![image](https://user-images.githubusercontent.com/8562436/29599029-a5b44cf6-8792-11e7-916f-09e5f0a249ee.png)

**Comment by rychkog** [comment]
@JaviRpo Usually this kind of error happens when Angular hasn't recognized a component.
Could you show me your app's NgModel definition?
