### ISSUE TITLE
Proposal - allow renaming through the tree-controller

### ISSUE THREAD

**Issue by TMaster** [valor-software/ng2-tree#129]
Hi,

I thought it will be really cool to add a method in the tree-controller to transit the node in to renaming state.
So now the user  can add an Edit button and the node changes it's state to **beingRenamed**.

Please checkout the [commit](https://github.com/TMaster/ng2-tree/commit/d1a19f6abdb4ca8f9a727f6fe553a901f76534cc), I think it can be really useful.

If you find it good I will propose a pull request.

Thanks,
TMaster

**Comment by rychkog** [comment]
@TMaster Don't be shy - send a PR :)

**Comment by TMaster** [comment]
Feature was merged :)
