### ISSUE TITLE
'Tree' not displaying - binding error. 

### ISSUE THREAD

**Issue by katsuragi545** [valor-software/ng2-tree#13]
I've followed the instructions to install ng2-tree, but I get the following error when running my application: 

```
zone.js:388Unhandled Promise rejection: Template parse errors:
Can't bind to 'tree' since it isn't a known property of 'tree'. ("

            <tree [ERROR ->][tree]="tree"></tree>

"): HomeComponent@6:18
'tree' is not a known element:
1. If 'tree' is an Angular component, then verify that it is part of this module.
2. If 'tree' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("

            [ERROR ->]<tree [tree]="tree"></tree>

"): HomeComponent@6:12 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'tree' since it isn't a known property of 'tree'. ("

            <tree [ERROR ->][tree]="tree"></tree>

"): HomeComponent@6:18
'tree' is not a known element:
1. If 'tree' is an Angular component, then verify that it is part of this module.
2. If 'tree' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("

            [ERROR ->]<tree [tree]="tree"></tree>
```

I simply copy and pasted the code from the tutorial so I'm unsure why I'm getting errors. I'm using Angular 2 RC6 and I made sure to add TreeComponent inside 'declarations' within NgModule. I've also added CUSTOM_ELEMENTS_SCHEMA to my app.module.ts file. Any ideas?

**Comment by Rakesh-Harsha** [comment]
Facing Exactly the same problem, can someone help in fixing it.

Can't bind to 'tree' since it isn't a known property of 'tree'. ("
    <tree [ERROR ->][tree]="tree"></tree>
    "): TreeViewComponent@1:10
'tree' is not a known element:

**Comment by rychkog** [comment]
Guys, working on update to latest version of angular - should work then

**Comment by Tommytoe** [comment]
Having the same problem.
Is this due to the project not working or is this a mistake at my side?
In what timewindow can we expect an update?

**Comment by rychkog** [comment]
@Tommytoe npm should contain new version of the tree already which has version 1.0.0 due to update to newest angular

**Comment by nicolaskaco** [comment]
@rychkog same problem here. Have you solved it?

**Comment by maverikarsh** [comment]
I followed the instructions provided here [https://www.npmjs.com/package/ng2-tree#eyes-demo](url) for ng2-tree. However, I am not able to expand or collapse the tree nodes. There is no error displayed. Am I missing something.

**Comment by WilburZjh** [comment]
@maverikarsh same problem still not know how to fix it

**Comment by rychkog** [comment]
@maverikarsh @WilburZjh @nicolaskaco 
Guys, please, try to reproduce it here so that I could help
https://stackblitz.com/edit/angular

**Comment by xdw898618984** [comment]
> @maverikarsh同样的问题仍然不知道如何解决它



> @maverikarsh同样的问题仍然不知道如何解决它

Have you solved the problem?I'm confused!
