### ISSUE TITLE
Not able to hide children on the initial Page Load

### ISSUE THREAD

**Issue by harigura** [valor-software/ng2-tree#135]
Hi,
   I am using ng2-tree library for my Angular 4 project. I am able to render the tree view but I am not able to hide the children on the initial page load. Here it how I am using the ng2-tree component:

Created a treeModel and gave it some id value and some children:

public tree: TreeModel = {
      value: 'Case',
      id: 111,
      children: [
        {
          value: 'Object-oriented programming'
        },
        {
          value: 'Prototype-based programming',
        }
      ]
    };

ngOnInit(): void {
    this.formGroup = this.fb.group({});

    this.service.getelements(0).then((data) => {
      for (let x of data) {

        let params = {
          value: x.name,
          id: x.objectID,
          child: x.child,
          children: [{value: 'empty'}]
        };
        this.treeArr.push(params);
      }

      let treeCon = this.treeRef.getControllerByNodeId(111);
      treeCon.setChildren(this.treeArr);
    });
  }

So On Page Load it is showing the nodes children as empty and if I am giving an empty children array then it is not allowing me to click and expand as it is considering all the children even though they have further more children is behaving like a leaf.

Can you help me out where I am going wrong

**Comment by rychkog** [comment]
@harigura Could you please, reproduce it here https://stackblitz.com/edit/angular ?
This way I will help you much faster

**Comment by harigura** [comment]
I got this fixed. My tree was not able to load the styles from ngTree.scss file so I added it as a separate file in my assets folder. Thanks
