### ISSUE TITLE
get controller of a node when it is created

### ISSUE THREAD

**Issue by Usamanawaz** [valor-software/ng2-tree#145]
When i create a node how can i get the controller of a node in the on Created function where i am getting the NodeEvent

<tree #treeFFs
                [tree]="ffs"
                (nodeCreated)="onNodeFFSCreated($event)">
          </tree>

 public onNodeCreated(e: NodeEvent, controller): void {
   // use controller
  }
when we create a node from template by default the id is set to undefined. and documentation says that we can get controller of a node only if we have set an id for the node. but by default the id is undefined.

Thanks.

**Comment by rychkog** [comment]
@Usamanawaz You are right - this is an issue in the design - will fix ASAP.
