### ISSUE TITLE
no controller for root if set in ngAfterViewInit

### ISSUE THREAD

**Issue by JanEggers** [valor-software/ng2-tree#146]
```
<tree  [tree]="root"  >      </tree>

ngAfterViewInit({
    setTimeout(() => {
    this.root = {
            id: 1,
            value: "root"
    };

    var controller = this.tree.getControllerByNodeId(1);
    if (!controller) {
        return false;
    }
    controller.expand();
});
});
```

i cannot programmaticly expand my root node because getControllerByNodeId returns null.

that is even true if i use settimeout after setting root

**Comment by rychkog** [comment]
@JanEggers Try to initialize `this.tree` in the `ngOnInit` or in a constructor.

Seems like in your fragment you try to fetch a controller before the tree is actually initialized with a `this.root`

```typescript
<tree  [tree]="root"></tree>

ngAfterViewInit({
    setTimeout(() => {
    this.root = {
            id: 1,
            value: "root"
    };

    var controller = this.tree.getControllerByNodeId(1);
    if (!controller) {
        return false;
    }
    controller.expand();
});
});
```

**Comment by JanEggers** [comment]
@rychkog   that code is just a simplified repro. i initialize root in the ctor with a dummy object and then fetch the real data from server.

i investigated further, the tree.rootcomponent.tree has the new data but tree.rootcomponent.controller.tree has still the old data.

![image](https://user-images.githubusercontent.com/6747376/31982386-f49bbf46-b958-11e7-9265-f407d94331de.png)

**Comment by JanEggers** [comment]
@rychkog pr incoming pls have a look

**Comment by JanEggers** [comment]
works with rc2
