### ISSUE TITLE
how to change the arrow icon

### ISSUE THREAD

**Issue by dyh333** [valor-software/ng2-tree#16]
hi, @rychkog . i want to change the arrow icon. and i found the source icon seems like that : folder-icon = '\25B6' in the styles folder.  so i want to know if it is a third lib? or something else? thanks.

![image](https://cloud.githubusercontent.com/assets/1221313/20693254/10a20a46-b618-11e6-80d3-4aebf2d22e9f.png)

**Comment by rychkog** [comment]
For now all the styles have default encapsulation strategy - in order to easy override defaults I should disable encapsulation. It is the fastest solution I think. Will publish new version once this is ready

**Comment by dyh333** [comment]
thanks, @rychkog , i am looking for it.
