### ISSUE TITLE
Menu Customization (enhancement)

### ISSUE THREAD

**Issue by robinmaple** [valor-software/ng2-tree#161]
Hi folks,

Great component, and I really enjoyed it. A quick question, is there a way to customize my menu options and labels (e.g. support for customized label and i18n for other languages)?

If it's not currently supported, please consider it as a future enhancement. Currently using it as a static tree, but wishing to utilize more functionalities as it expands.

Thanks!

**Comment by rychkog** [comment]
Thasnk, @robinmaple!
We have an [issue](https://github.com/valor-software/ng2-tree/issues/25) regarding this. Agree that it should be there
