### ISSUE TITLE
How to load children when parent expand from web service 

### ISSUE THREAD

**Issue by afsalcodehack** [valor-software/ng2-tree#165]
How to load children when parent expand from web service . i need to call all parent first then i want to load child on expand parent instead of hard coding in tree data

 ```
value: 'Prototype-based programming',
        loadChildren: (callback) => {
          setTimeout(() => {
            callback([
              {value: 'Input Mono', id: 19},
              {value: 'Roboto Mono', id: 20},
            ]);
          }, 100);
```
 or how to manage loadChildren function from expand event

**Comment by rychkog** [comment]
@afsalcodehack Async children are collapsed by default and get loaded only when you click on expand.
So all you parent should have async loaded children and it should work.

Also, there was an issue on [how to load nested async children](https://github.com/valor-software/ng2-tree/issues/75)

**Comment by afsalcodehack** [comment]
is there any flag like haveChildren because children will load later from server and there is chance might not have any children this case all parent show expand icon in every node

**Comment by rychkog** [comment]
@afsalcodehack There is a function that [does exactly this](https://github.com/valor-software/ng2-tree/blob/master/src/tree.ts#L353)
It is in the [Tree class](https://github.com/valor-software/ng2-tree#tree-class)
