### ISSUE TITLE
Can't bind to 'tree' since it isn't a known property of 'tree'. ("

### ISSUE THREAD

**Issue by zyj1022** [valor-software/ng2-tree#17]
```
Can't bind to 'tree' since it isn't a known property of 'tree'. ("
   <tree [ERROR ->][tree]="tree"></tree>
   "): HomeComponent@1:9
'tree' is not a known element:
1. If 'tree' is an Angular component, then verify that it is part of this module.
2. If 'tree' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
   [ERROR ->]<tree [tree]="tree"></tree>
   "): HomeComponent@1:3 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'tree' since it isn't a known property of 'tree'. ("
   <tree [ERROR ->][tree]="tree"></tree>
   "): HomeComponent@1:9
'tree' is not a known element:
1. If 'tree' is an Angular component, then verify that it is part of this module.
2. If 'tree' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
   [ERROR ->]<tree [tree]="tree"></tree>
   "): HomeComponent@1:3
```
According to the tutorial in the readme, cannot normal use, the demoIn the code is dependent on the development kit, independence should do a simple example, it is easier to use

**Comment by rychkog** [comment]
@zyj1022 I've updated tutorial and new version was released. Thanks for your suggestion regarding `demo` - will consider this

**Comment by jithinjohnkaniyampoikayil** [comment]
Hi i had an **issue when trying to load the TreeModule** .  I have **solved this issue**. The problem was with the @angular/cli version . In the package.config file inside _\node_modules\ng2-tree_ change  
` "devDependencies": {
    "@angular/cli": "1.1.1",
} `
to 
` "devDependencies": {
    "@angular/cli": "#####",// version of your @angular/cli(**You can find it from package.config file in the root folder**)
} `

**Comment by rogercoder** [comment]
I also have this problem:

`Can't bind to 'tree' since it isn't a known property of 'tree'`

Have fiddled with my project's package.json but no luck.

**Comment by rychkog** [comment]
@rogercoder Please, provide your Angular dependencies' versions

**Comment by rogercoder** [comment]
Thanks for the quick response ... but I actually got it working with angular-cli 1.6.8. (I could not get it to work properly with angular-cli 1.7.0-rc.0 for what it's worth, but that may be because of problems unrelated to ng2-tree).

My problem was I had imported TreeModule into our SharedModule but had neglected to add it to the exports section of that module.

**Comment by rychkog** [comment]
@rogercoder Thank you for sharing this!

**Comment by l2018ng** [comment]
This the version I am using:    "ng2-tree": "2.0.0-alpha.10",

**Comment by rychkog** [comment]
@l2018ng Unfortunately you need to move to Angular 5. Cause there is a backward compatibility issue between Angular 4 and 5.

**Comment by rychkog** [comment]
Then you can start using latest versions of the tree

**Comment by Lars-Erik75** [comment]
Same issue with Angular 5

"dependencies": {
    "angular/animations": "^5.2.0",
    "angular/common": "^5.2.0",
    "angular/compiler": "^5.2.0",
    "angular/core": "^5.2.0",
    "angular/forms": "^5.2.0",
    "angular/http": "^5.2.0",
    "angular/platform-browser": "^5.2.0",
    "angular/platform-browser-dynamic": "^5.2.0",
    "angular/router": "^5.2.0",
    "ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "ngx-translate/core": "^9.0.1",
    "bootstrap": "4.0.0",
    "core-js": "^2.5.2",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.4",
    "ng2-tree": "^2.0.0-rc.9",
    "rxjs": "^5.5.5",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "angular/cli": "~1.6.5",
    "angular/compiler-cli": "^5.2.0",
    "angular/language-service": "^5.2.0",
    "biesbjerg/ngx-translate-extract": "^2.3.1",
    "ngx-rocket/scripts": "^2.0.0",
    "types/jasmine": "^2.5.52",
    "types/jasminewd2": "^2.0.2",
    "types/lodash": "^4.14.52",
    "types/node": "^8.0.10",
    "codelyzer": "^4.1.0",
    "hads": "^1.3.4",
    "htmlhint": "^0.9.13",
    "https-proxy-agent": "^2.0.0",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "^4.1.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "~5.2.2",
    "puppeteer": "^1.0.0",
    "stylelint": "~8.4.0",
    "stylelint-config-recommended-scss": "~3.0.0",
    "stylelint-config-standard": "~18.0.0",
    "stylelint-scss": "~2.2.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

**Comment by rogercoder** [comment]
@Lars-Erik75 Try angular-cli 1.6.8

**Comment by Lars-Erik75** [comment]
@rogercoder  Thx for answer. 
Same error after uninstalling Angular-cli and reinstalling with 1.6.8 though.

**Comment by rychkog** [comment]
@Lars-Erik75 Please, reproduce you error using https://stackblitz.com
This will allow to understand the cause of the issue much faster.

**Comment by cdiaz** [comment]
I also have this same problem
 I am using: 
"ng2-tree": "2.0.0-rc.11",
"@angular/cli": "~1.7.4"

**Comment by amali1025** [comment]
still can't fix it

**Comment by NahidaHK** [comment]
Hi .. You need to add this in your app.module.ts

import { TreeModule } from 'ng2-tree';

imports: [ ... , TreeModule  , ...]

Hope that helps You.

**Comment by lewislacook** [comment]
I'm also having this issue, using
"@angular/cli": "1.7.4",

"ng2-tree": "^2.0.0-rc.11"

**Comment by kik-doctor** [comment]
Hi, Developers.
There is no any solution for this issues.
I think that everyone in here is not real and loyal developer.
Selfish one.

**Comment by roshanaale9818** [comment]
it is not calling the method when clicked on (activate)="onSelect(tree,$event)"?
