### ISSUE TITLE
AOT build fails

### ISSUE THREAD

**Issue by encool** [valor-software/ng2-tree#182]
There is an Angular-cli project use ng2-tree.Running  ```ng serve```  is ok but when I run ```ng serve --aot```  It comes with errors
```
ERROR in ./node_modules/._ng2-tree@2.0.0-rc.4@ng2-tree/src/tree.component.ngfactory.js
Module build failed: Error: C:\Users\qiao\angular_wp\ng2-easyui\node_modules\._ng2-tree@2.0.0-rc.4@ng2-tree\src\tree.component.ngfactory.js is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\qiao\angular_wp\ng2-easyui\node_modules\._@ngtools_webpack@1.8.4@@ngtools\webpack\src\angular_compiler_plugin.js:625:23)
    at plugin.done.then (C:\Users\qiao\angular_wp\ng2-easyui\node_modules\._@ngtools_webpack@1.8.4@@ngtools\webpack\src\loader.js:467:39)
 @ ./src/app/ng2-tree/ng2-tree.demo.component.ngfactory.js 11:0-82
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
environment
```Angular CLI: 1.5.4
Node: 6.11.1
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.1
@angular/cli: 1.5.4
@angular/material: 5.0.0-rc.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

```

**Comment by encool** [comment]
I think the published angular lib should follow the Angular Package Format [which in this doc described](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) while ng2-tree seems not.

**Comment by rychkog** [comment]
@encool Why do you have path a like that `._ng2-tree@2.0.0-rc.4@ng2-tree`? Have you symlinked tree into your project?

**Comment by encool** [comment]
I am in china,for the speed reason I use cnpm instead of npm,Maybe that cause the path problem?..I am not sure.
However I am using angular material and other third party lib did not cause errors.
I will try it agian with npm.

**Comment by rychkog** [comment]
@encool Please, keep me posted - hope we'll solve this

**Comment by encool** [comment]
Use ```npm install``` reinstall all the packages,It works as expected. 
Just config like this ```npm config set registry https://registry.npm.taobao.org``` rather than use ```cnpm``` for the sake of speed.
Can be closed,Thanks for the response.
