### ISSUE TITLE
Metadata mismatch in RC 4

### ISSUE THREAD

**Issue by TMaster** [valor-software/ng2-tree#183]
Hi
I updated the tree to the latest version (**2.0.0-rc.4)** but my app crashes on :

> Metadata version mismatch for module ... found version 4, expected 3

When I use the repository to retrieve the source code instead of the package it works fine.

angular dependencies: 
```
  "@angular/animations": "^4.2.3",
    "@angular/common": "^4.2.3",
    "@angular/compiler": "^4.2.3",
    "@angular/core": "^4.2.3",
    "@angular/forms": "^4.2.3",
    "@angular/http": "4.2.3",
    "@angular/platform-browser": "^4.2.3",
    "@angular/platform-browser-dynamic": "^4.2.3",
    "@angular/router": "^4.2.3",
```

Can you please help?

thanks,
TMaster

**Comment by rychkog** [comment]
@TMaster This is because rc4 uses Angular 5 and it is not compatible with Angular 4. Unfortunately, the only way to use libs that use Angular 5 is to upgrade your app to Angular 5 :(

**Comment by TMaster** [comment]
Ok, I'll check it out as soon as I'll upgrade to ng5
