### ISSUE TITLE
Stop moving node based on condition

### ISSUE THREAD

**Issue by shafeekv** [valor-software/ng2-tree#185]
Hello,

How can I stop dragging a particular node/based on some condition?
Your response is appreciated!

Thanks,
Shafeek

**Comment by shafeekv** [comment]
Hi, is this feature supported now?  Some scenarios
1: I want to restrict dragging a node to a node to another node which has a child with same value (duplicate node)
2: I want to cancel moving if the a particular  node/or group of nodes moved to incompatible node (ex: book items moved to toys node)

Assistance is appreciated!

Thanks

**Comment by rychkog** [comment]
@shafeekv No, this is currently unsupported. You cannot move node onto static nodes (this is only option available currently).
But this is a very fair use-case.

**Comment by shafeekv** [comment]
Thanks @rychkog for the update.
I am handling the scenario with error alerts to users and blocking them from final operations.
Anyway thanks again for the nice component which helped me very much
