### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by leompande** [valor-software/ng2-tree#188]
Am using it with angular4 and I get this in dev server

ERROR in Error: Metadata version mismatch for module ..../node_modules/ng2-tree/index.d.ts, found version 4, expected 3, resolving symbol AppModule in ....src/app/app.module.ts, resolving symbol AppModule in .../src/app/app.module.ts

**Comment by AndriWandres** [comment]
Getting the same Error as well with Angular 4

**Comment by jyotimishra12** [comment]
Does this issue resolved? 
I am also getting this issue:
node_modules/ng2-tree/src/menu/menu.events.d.ts, found version 4, expected 3.

Anyone please help.

**Comment by CrazyBBer** [comment]
also got this issue.

**Comment by lawmbass** [comment]
Just got this error today. Does anyone know how to resolve this?

**Comment by lawmbass** [comment]
Upgrading my Angular app from V4 to V5 seemed to fix the issue for me.

**Comment by CrazyBBer** [comment]
> also got this issue.
check your framework or starter  dependency version .
change it to the right version that your  framework or starter  depends on

**Comment by rychkog** [comment]
The new version of tree works only with Angular 5. This is because module format from Angular 4 is not compatible with the one from Angular 5

**Comment by JSponaugle** [comment]
Hello,

   What Version of ng2-tree works in Angular 4. Our client has not decided to move to angular 5 yet and we are running into this issue.

**Comment by rychkog** [comment]
@JSponaugle I think  ng2-tree 2.0.0-alpha10 work with Angular4 but it might miss some features/fixes.

**Comment by Fiotz** [comment]
I have the same issue, I upgraded my angular to version 5.2.9, but I continues to have the same problem
