### ISSUE TITLE
Is there any chance to change the node name's color base on the data of the node ?

### ISSUE THREAD

**Issue by yoyogis** [valor-software/ng2-tree#194]
Is there any chance to change the node name's color base on the data of the node ?

**Comment by yoyogis** [comment]
item.toString = function () {
      return `<span style='color:${statusColor[this.status]}'>${this.name}</span>`;
}

I know the answer, Rewrite the toString() method, let it return a node.

**Comment by rychkog** [comment]
@yoyogis Actually - this is a good point for documentation

**Comment by rychkog** [comment]
Thanks!
