### ISSUE TITLE
Hi, I want to extend the right-click function? What can I do ?

### ISSUE THREAD

**Issue by MIseChow** [valor-software/ng2-tree#198]
I don't know how to extend another right-click button, except modify the source code, has other ways to achieve it ?
Thank you for you answers!

**Comment by mmirzaeyan** [comment]
what do you mean about another right click ? do you want a custom context in right click ?

**Comment by MIse3uc** [comment]
@mmirzaeyan Yes, that's what I mean. Where can I change his code to implement my functionality?

**Comment by MIse3uc** [comment]
@mmirzaeyan  Ok, i get it. Thank you very much!

**Comment by MIse3uc** [comment]
I think i did the same thing as you.

app.component.html
<tree #treePages [tree]="tree" **(menuItemSelected)="onMenuItemSelected($event)"** [settings]="settings" (nodeMoved)="handleMoved($event)" (nodeRenamed)="handleRenamed($event)"
        (nodeRemoved)="handleRemoved($event)" (nodeSelected)="handleSelected($event)" (nodeCreated)="handleCreated($event)">
      </tree>

app.component.ts :
nodeMenuItem = [
    { action: NodeMenuItemAction.NewTag, name: 'New File', cssClass: 'fa fa-file-o' },
    { action: NodeMenuItemAction.NewFolder, name: 'New Folder', cssClass: 'fa fa-folder-o' },
    { action: NodeMenuItemAction.Rename, name: 'Rename', cssClass: 'rename' },
    { action: NodeMenuItemAction.Remove, name: 'Delete', cssClass: 'remove' },
    { action: NodeMenuItemAction.Custom, name: 'NodeOptions', cssClass: 'fa fa-cog' }
  ];

private onMenuItemSelected(e) {
    switch (e.selectedItem) { 
      case 'NodeOptions':    // **to do Everythings according to different name**
        const url = prompt('Plearse Enter Your Website', 'http://');
        const node = e.node.node;
        node.url = url;
        this.ajax('updataUrl', node);
        break;

      default:
        break;
    }
  }

**Comment by rychkog** [comment]
@MIseChow Have you resolved your issue?

**Comment by MIseChow** [comment]
@rychkog yes,i already resolved my issue.Thanks~
