### ISSUE TITLE
can not move a element to a empty folder if the element original position is the sibling with the folder

### ISSUE THREAD

**Issue by thrillerwu** [valor-software/ng2-tree#208]
If original case is 
>root ---folder
>>|__element

I find i can not move element to the folder. I find these code prevent the case

> 37         this.subscriptions.push(this.treeService.draggedStream(this.tree, this.element)
>  38             .subscribe(function (e) {
>  39             if (_this.tree.hasSibling(e.captured.tree)) {
>  40                 _this.swapWithSibling(e.captured.tree, _this.tree);
>  41             }   
>  42             else if (_this.tree.isBranch()) {
>  43                 _this.moveNodeToThisTreeAndRemoveFromPreviousOne(e, _this.tree);
>  44             }   
>  45             else {
>  46                 _this.moveNodeToParentTreeAndRemoveFromPreviousOne(e, _this.tree);
>  47             }

I try to fix line 39 to
`if (!_this.tree.isBranch() && _this.tree.hasSibling(e.captured.tree)) {`
Then I can get the correct result.

**Comment by rychkog** [comment]
@thrillerwu Please check is it the same as https://github.com/valor-software/ng2-tree/issues/206?

**Comment by rychkog** [comment]
If not - then please give me a bit more context, so that I can reproduce. Or create a gif image with the issue (this way it will be even better).

**Comment by thrillerwu** [comment]
yes, it's the same as #206. Will you fix the case in future version?  @rychkog

**Comment by rychkog** [comment]
@thrillerwu Sure, cannot say you the exact time when a new release will be available. Currently, I'm working on issue prioritization so that I can split them on chunks

**Comment by akshaygolash** [comment]
@rychkog Is there any update when this will be fixed?
