### ISSUE TITLE
Tree element is hidden when collapsed + root is invisible on init

### ISSUE THREAD

**Issue by ctolene** [valor-software/ng2-tree#209]
Using `rootIsVisible: false` and `'isCollapsedOnInit': true` together will hide the tree element completely rather than just initializing with the roots child nodes visible & collapsed.

**Comment by ctolene** [comment]
**Workaround** 
Add settings to child node: 
app settings = `{rootIsVisible: false}`
root node settings = `{'isCollapsedOnInit': false}`
child node settings = `{'isCollapsedOnInit': true}`

**Comment by rychkog** [comment]
@ctolene Thanks for this! - subtle issue.

**Comment by SSKhandade** [comment]
With asynchronous loading Tree root node is being hidden. **But child nodes are not loading.** Here are the following settings are done.

<tree [tree]="tree" [settings]="settings"> </tree>

 public settings: Ng2TreeSettings = {
     rootIsVisible: false
   };

When rootIsVisible is true then it loads tree with root
