### ISSUE TITLE
Static Tree functionality

### ISSUE THREAD

**Issue by sjdemoor** [valor-software/ng2-tree#21]
Is it possible to disable the ability to edit (remove, rename, move, create) node elements?  A flag for disabling editing (either globally, and/or at a node level) would be useful.

**Comment by rychkog** [comment]
@sjdemoor Agree!

**Comment by Taifuru** [comment]
I need this too!

**Comment by tplessis** [comment]
+1!

**Comment by sjdemoor** [comment]
👍  Thanks for turning this so quickly!
