### ISSUE TITLE
How do I disable drag and drop functionality?

### ISSUE THREAD

**Issue by manojp1988** [valor-software/ng2-tree#215]
Hi, 

I want to disable drag and drop functionality. How can I do this with ng2-tree?

**Comment by manojp1988** [comment]
I just saw there is a property called static, but this property also disables menu functionality.  I still need 
menu items on right click.
>  settings: {
>           'static': true
>         },

**Comment by rychkog** [comment]
@manojp1988 Currently there is no option for disabling only DnD functionality

**Comment by ketanp-iprogrammer** [comment]
Hi @rychkog  , any other  way we can disable drag and drop in ng2-tree ? 
Any help would be appreciated . 
Thanks

**Comment by glueornose** [comment]
This can be achieved by making a PreventMouseDown-directive:

import { Directive, HostListener } from "@angular/core";

@Directive({
    selector: "[prevent-mousedown]"
})
export class PreventMouseDown {
    @HostListener("mousedown", ["$event"])
    public onClick(event: any): void {
        event.preventDefault();
    }
}

.. and then using this directive within the tree:

<tree prevent-mousedown [tree]="tree" [settings]="settings"></tree>
