### ISSUE TITLE
Cannot find .config/umd.bundler.js

### ISSUE THREAD

**Issue by daniel4thsource** [valor-software/ng2-tree#22]
Hey guys!  Having trouble forking and using this repo. Can't find : .config/umd.bundler.js   Looks like it's been exclude in the gitignore file.

**Comment by lovery** [comment]
Hi!
I ran into the same problem, when I tried to install dependencies.
I found that this file was added to git ignore in this commit b407b761ebb6bc47e7dc36a8823bae5d7b916fc
Also there was a script in package.json, which calls this file in the same commit.

I've removed the script, which calls this file and managed to keep going, but it will be nice to know what is the content of this file.

**Comment by lovery** [comment]
Hi,
I dug more into this problem and I realized that in package.json the script calls a file - .config/umd-bundler.js.
In the .gitignore the line is !./.config/umd.bundler.js which means that it this file .config/umd.bundler.js is added explicitly to be tracked in the repository
The files are not the same, so I guess that  @rychkog misspelled it in the .gitignore.

It will be great if he manage to add it soon.

**Comment by lovery** [comment]
Hi @daniel4thsource,

I've just find a way to get this file.
In case you need it you can find it from [here](https://github.com/lovery/ng2-tree/blob/master/.config/umd-bundler.js).
Those days I will send a pull request for this and a few other features.

Happy New year!

**Comment by rychkog** [comment]
@daniel4thsource, @lovery I've added this file - sorry for this - didn't pay attention that it was not included in commit :(

**Comment by rychkog** [comment]
@lovery Looking forward for PRs! :)
