### ISSUE TITLE
getControllerByNodeId() not available on tree component

### ISSUE THREAD

**Issue by ctolene** [valor-software/ng2-tree#226]
The example in the documentation for getControllerByNodeId() doesn't work. The method is not available on the object. Is this a bug? See comments in code below for output.

**HTML**
`<tree [tree]="tree" #treeComponent></tree>`
**TypeScript**
```
@Component({...})
export class AppComponent implements OnInit, AfterViewInit {{
	...
	public tree: TreeModel = {
		value: 'TestParent',
		id: 0,
		children: [{
			'value': 'TestChild',
			id: 1,
			...
		}]
	};
	@ViewChild('treeComponent') treeComponent;
	public ngAfterViewInit(): void {
		const oopNodeController = this.treeComponent.getControllerByNodeId(1);
		console.log(oopNodeController); // <----- Returns null
		console.log(this.treeComponent);
		/* ^ "this.treeComponent" Exposes:
			loadNextLevel
			menuItemSelected
			nodeChecked
			nodeCollapsed
			nodeCreated
			nodeExpanded
			nodeMoved
			nodeRemoved
			nodeRenamed
			nodeSelected
			nodeUnchecked
			nodeUnselected
			rootComponent
			subscriptions
			template
			tree
			treeModel
			treeService
		*/
	}
}
```

**Comment by rychkog** [comment]
@ctolene It works, please check here https://stackblitz.com/edit/angular-rgcuga?file=app/hello.component.ts
Try to modify the example in order to reproduce your issue

**Comment by ctolene** [comment]
I figured out the issue. Because I am hiding the root node in the constructor it makes `getControllerByNodeId` unusable for child nodes. Adding the following in your example reproduces the issue.
```
import { TreeInternalComponent } from 'ng2-tree/src/tree-internal.component';

constructor(){
    TreeInternalComponent.prototype.ngOnInit = function () {
      this.settings = { rootIsVisible: false };
    }
}
```

**Comment by rychkog** [comment]
@ctolene This is something :) Will have a look

**Comment by rychkog** [comment]
@ctolene But why do you have settings assigned this way. It works fine when you pass settings as an input to the tree. `[settings]="settings"`

**Comment by ctolene** [comment]
@rychkog Absolutely perfect, that's exactly what I needed. Thank you for your help!

**Comment by ctolene** [comment]
Well, the fixed work, but also created more issues. When initializing the settings directly on the element using your recommendation, these settings will no longer work:
```
settings: {
  static: true,
  isCollapsedOnInit: false,
  rightMenu: false,
  leftMenu: false,
  menuItems: [
	{ action: NodeMenuItemAction.Custom, name: 'Add', cssClass: '' },
	{ action: NodeMenuItemAction.Remove, name: 'Remove', cssClass: '' },
	{ action: NodeMenuItemAction.Rename, name: 'Rename', cssClass: '' }
  ]
}
```
Reproduced here: [https://stackblitz.com/edit/angular-ejm5ng?embed=1&file=app/hello.component.ts](https://stackblitz.com/edit/angular-ejm5ng?embed=1&file=app/hello.component.ts)

**Comment by ctolene** [comment]
The below works. Thanks again for your help, really appreciate your time and also thank you for this application. Cheers, Cody.

```
import { Component, Input, ViewChild, AfterViewInit } from '@angular/core';
import { TreeModel, NodeEvent, NodeMenuItemAction, Ng2TreeSettings } from 'ng2-tree';

@Component({
  selector: 'hello',
  template: `<tree [tree]="tree" [settings]="settings" #treeComponent></tree>`,
})
export class HelloComponent {
  public tree: TreeModel = {
    settings:{
      static: false,
      isCollapsedOnInit: false,
      rightMenu: true,
      leftMenu: false,
      menuItems: [
        { action: NodeMenuItemAction.Custom, name: 'Add', cssClass: '' },
        { action: NodeMenuItemAction.Remove, name: 'Remove', cssClass: '' },
        { action: NodeMenuItemAction.Rename, name: 'Rename', cssClass: '' }
      ]
    },
		value: 'TestParent',
		id: 0,
		children: [{
			value: 'Child 01',
			id: 1
		},{
			value: 'Child 02',
			id: 2,
      children: [{
        value: 'Child A',
        id: 4
      },{
        value: 'Child B',
        id: 5
      }]
		},{
			value: 'Child 03',
			id: 3
		}]
	};

  settings: Ng2TreeSettings  = {
      rootIsVisible: false
  }
}

```

**Comment by rychkog** [comment]
@ctolene There are 2 kinds of settings. [The first kind](https://github.com/valor-software/ng2-tree#settings)([Ng2TreeSettings](https://github.com/valor-software/ng2-tree/blob/master/src/tree.types.ts#L115)) is for tree component itself and the second one is for the actual [tree model](https://github.com/valor-software/ng2-tree#configure-node-via-treemodelsettings)([TreeModelSettings](https://github.com/valor-software/ng2-tree/blob/master/src/tree.types.ts#L56)). All of them have different purposes

Ng2TreeSettings is kinda component-wide settings that adjust behavior of the whole tree.
TreeModelSettings is a bit more granular thing which allows adjusting just certain aspects of each node.

**Comment by praveenhariyala** [comment]
Hi i have same issue like **this.GenericScopeTreeComponent.getControllerByNodeId is not a function**
![image](https://user-images.githubusercontent.com/17614243/45609641-c582b000-ba26-11e8-8247-39c184625bae.png)
can one help me out
