### ISSUE TITLE
Can't import TreeModule

### ISSUE THREAD

**Issue by sadplace** [valor-software/ng2-tree#23]
Hi, i really like your tree but i install it and can't get it to work.

I follow your read me but It gives this error:
Uncaught Error: Unexpected value 'TreeModule' imported by the module 'OrganizationModule'

**Comment by midu2903** [comment]
I get the same issue.

**Comment by piyushgupta1** [comment]
Same Issue

**Comment by nicolaskaco** [comment]
Does anyone have this working? I need an example ASAP!!

**Comment by rychkog** [comment]
@nicolaskaco, @piyushgupta1  Which version of angular do you use? I need to reproduce this in order to fix.

**Comment by sadplace** [comment]
hi,

i have the latest version

**Comment by rohitsd2** [comment]
Hi,
I have same issue with  'TreeModule'.
I didn't found reason behind it but If you are trying with "npm install --save ng2-tree" then this issue will occur.
To resolve this issue please download the provided zip and rename it to ng2-tree and paste it into your node_modules It will resolve the issue.

**Comment by piyushgupta1** [comment]
@rychkog 
 i am using Angular@2.4

**Comment by nicolaskaco** [comment]
@rohitsd2 but when I do  "npm install --save ng2-tree" has a folder named 'bundles' and if I cloned the git that folder doesn't exist.

When I do the npm install it breaks the rest of the code...

**Comment by rychkog** [comment]
@rohitsd2, @nicolaskaco, @piyushgupta1, @sadplace, @midu2903 
Guys all of you have your build environment. I've built demo project and put there ng2-tree with deps updated. Tree in there does work. If it still doesn't in your case than I need more info on how to reproduce this issue.

At the bottom of my comment in this issue (https://github.com/valor-software/ng2-tree/issues/26) (which is essentially a duplicate) I've put a link to this demo project. Please have a look at this project and if it won't help you with this, then I will need more info about your envs and maybe you can build simple project like the one I've built that reproduces this issue. In this case I will fix it. Thanks for your help!

**Comment by lovery** [comment]
Hello,
I end up with the same error when I try to get package from a repository.
If I install the app in the normal way - with `npm install ng2-tree` there is no problems,
but when I try to install it from the repository the error is there.

**Comment by lovery** [comment]
I've found out what was my problem - I was missing the *.metadata.json files, when installing from a repository.

**Comment by rychkog** [comment]
@lovery *.metadata.json files were missing in ng2-tree build?

**Comment by lovery** [comment]
Yes, but it was my fault. I was trying to install the package from my github repository and forget to add those files.

**Comment by rychkog** [comment]
@lovery Thanks for collaboration!

**Comment by jithinjohnkaniyampoikayil** [comment]
Hi i had an **issue when trying to load the TreeModule** .  I have **solved this issue**. The problem was with the @angular/cli version . In the package.config file inside _\node_modules\ng2-tree_ change  
` "devDependencies": {
    "@angular/cli": "1.1.1",
} `
to 
` "devDependencies": {
    "@angular/cli": "#####",// version of your @angular/cli(**You can find it from package.config file in the root folder**)
} `
