### ISSUE TITLE
getControllerByNodeId() is null

### ISSUE THREAD

**Issue by mrfx** [valor-software/ng2-tree#231]
const nn: TreeModel = { "some name", id:  2, children: [] }
this.treeComponent.rootComponent.controller.addChild( nn );
setTimeout(() => {
        console.info( 'result:', this.treeComponent.getControllerByNodeId( 2 ));
      }, 5000);

// returns null

I read #204 but  "createNode" solution does'nt work for me. :(

**Comment by rychkog** [comment]
@mrfx You can use [addChildAsync](https://github.com/valor-software/ng2-tree/issues/204#issuecomment-364765251). This is not yet documented but already available

**Comment by mrfx** [comment]
Yes. This works great! Now I can create my tree dynamically & recursively from other objects and structures. Thank you a lot!
