### ISSUE TITLE
Reload TreeModel Hook

### ISSUE THREAD

**Issue by dpollastrini** [valor-software/ng2-tree#233]
I'm populating my TreeModel from a backend Web API.  I have an Angular service that supplies the TreeModel via an observable.  My component subscribes to the observable and updates the tree as TreeModel updates are pushed from the service....

**Example Template**
```
<tree #scriptTreeComponent
    [tree]="scriptTreeModel"
    [settings]="scriptTreeSettings"
    (nodeSelected)="onScriptSelected($event)"
    (nodeCreated)="onScriptCreated($event)"
    (menuItemSelected)="onMenuItemSelected($event)"
></tree>
```

**Example Component Subscription**
```
...
      this.campaignService.campaignScriptTreeModel$.subscribe(
        (campaignScriptTreeModel: TreeModel) => {
          this.scriptTreeModel = campaignScriptTreeModel;
          this.scriptTreeModel.settings = {

            cssClasses: {
              expanded: 'fa fa-caret-down',
              collapsed: 'fa fa-caret-right',
              empty: 'fa fa-caret-right disabled',
              leaf: 'fa',
            },
            templates: {
              node: '<i class="fa fa-folder-o"></i>',
              leaf: '<i class="fa fa-file-o"></i>',
            },
            menuItems: [
              { action: NodeMenuItemAction.NewFolder, name: 'Add', cssClass: 'fa fa-arrow-right' },
              { action: NodeMenuItemAction.Custom, name: 'Archive', cssClass: 'fa fa-arrow-right' },
            ],
          };
          this.selectNode(this.selectedScriptId);
        },
      )
...
```

As you can see, I'm essentially reloading the entire TreeModel (and TreeSettings, as this seems to be necessary) when the subscription is updated.  Setting the scriptTreeModel updates the input on the TreeComponent, etc. This works fine and the tree renders the new content as expected.

However, my goal is to select (make active) a specific node once the TreeComponent is fully _reloaded_.  The problem seems to be that there's no way to tell when this occurs.  In my example, "selectNode" (which contains controller logic for getting and setting the referenced node id) fails since the TreeComponent is not actually done at this point. 

I've reviewed the existing events, but they seem to be related to individual node actions.  I'm wondering if having the ng2-tree tree.component ngOnChanges bubble an event from tree-internal.component might offer a hook for determining when a tree is fully _reloaded_ (with controllers, etc.).  Or am I missing an existing way this can be done.

Thanks for your help.  Loving the component.

**Comment by rychkog** [comment]
@dpollastrini Thanks for sharing this case! I'll label this issue as an enhancement. For now, you can try to select the tree in a next event loop iteration using `setTimeout`.
Please let me know whether that helped.

**Comment by dpollastrini** [comment]
@rychkog setTimeout works fine.  Thanks.
