### ISSUE TITLE
The Demo doesn't work

### ISSUE THREAD

**Issue by nicolaskaco** [valor-software/ng2-tree#24]
Hi, I'm trying to test it but the demo doesn't work.  Any idea why?

**Comment by SergeyKuryatnick** [comment]
Hi!
What demo do you mean?
What error do you have?

**Comment by nicolaskaco** [comment]
I downloaded this demo: https://github.com/valor-software/ng2-tree/tree/develop/demo and it is supposed to work like this: http://valor-software.com/ng2-tree/ but it doesn't.

**Comment by nicolaskaco** [comment]
@SergeyKuryatnick I need an example to understand how it is supposed to work because I will need to use it on a project and this is the best treeview for Angular 2.
Thanks!!

**Comment by SergeyKuryatnick** [comment]
You should clone full git package of ng2-tree, to start the demo. Not only demo folder:)

**Comment by nicolaskaco** [comment]
@SergeyKuryatnick  I downloaded the whole giti, it downloaded as a .zip and I extracted and it still doesn't work.
