### ISSUE TITLE
Add custom context menu

### ISSUE THREAD

**Issue by apriyadarshi38** [valor-software/ng2-tree#25]
Hi,
is it possible to make custom context menu.
my problem scenario is that i want to add custom context menu and implement there functionality accordingly.

Can we hide root node in tree?
 I am having array of tree node while mapping it to "TreeModel" data i need to add a dummy root node in array can we hide this in tree and how?

**Comment by rychkog** [comment]
@apriyadarshi38 For now it is impossible to do both: custom context menu and hidden root.
Currently I am working on a custom context menu.

**Comment by rychkog** [comment]
@apriyadarshi38 Can you give an example of customized context menu and couple use cases?

**Comment by apriyadarshi38** [comment]
customized context menu means
we can give different context menu for different node in tree.
while right click on top this will show different menu and for different children it shows different

**Comment by jycouet** [comment]
Hi, 
Thank you @rychkog, your first commit about hide root seems nice :)
Can you upload it in the npm package?

On my side, I would like to disable (remove) this menu. How could I do that?

Thank you

**Comment by rychkog** [comment]
@jycouet Today I'll publish new alpha version. This will be available in there. Also you can read about this feature in the [development branch doc](https://github.com/valor-software/ng2-tree/blob/develop/README.md)

**Comment by rychkog** [comment]
@jycouet ng2-tree@2.0.0-alpha.2 is out

**Comment by jycouet** [comment]
@rychkog thx :)

**Comment by vishals82** [comment]
Any plan to merge custom menu changes?

**Comment by rychkog** [comment]
@vishals82 There is no PR with that feature

**Comment by JohnArrowwood** [comment]
+1 - I need the ability to define my own menu:

* Edit
* Cut
* Copy
* Paste
* Link
* Delete

I'm okay with it being the same for all nodes, but I need to be able to distinguish which menu item was selected.

If this is already doable, how is it done?  Thanks!

**Comment by avadhootha** [comment]
@rychkog  - This tree view is too good and I see you have added multiple features to the tree over past year. I couldn't see any other package having context menu and these many configurable options.

Perhaps you could help me with this issue of existing Context menu?

I need to have only three of the options  - create(Only New Node), edit and delete. I want to use this tree to show a schema hierarchy. So, there wont be any folder in our case.  Is it possible to rename already existing menu options (to "Add Model, Edit, Delete" )or create a custom menu (for any additional options in menu like copy) ?
Thanks

**Comment by rychkog** [comment]
@avadhootha @JohnArrowwood Menu is one of the soft spots in the current implementation - it is hardcoded for now, but definitely should be redesigned and made configurable.
I will add this for sure but cannot say when... If you want to implement it on your own or know a person who wants, please - go ahead and do it. We need to grow a community around this project.

**Comment by avadhootha** [comment]
@rychkog  Thanks for the quick response. 
Currently, for my use case I modified the hard coded Menu options from the source code, compiled and using the package.  Will try to work on implementing configurable options and post it here.

**Comment by rychkog** [comment]
@avadhootha That would be super helpful!

**Comment by avadhootha** [comment]
@rychkog The above Referenced issue(#143) is not related to this issue. Perhaps you might want to link that to #147. 

@vishals82 @JohnArrowwood 
My code is a little messy but I got it to work to configure custom menu items. Here I am attaching the code changes. 
 https://github.com/valor-software/ng2-tree/commit/fc9f1553ab148e513030c1f989a7517e6522ed80

@rychkog - I am sorry that there are travis cli build issues in the PR Request raised(#159), which I think are due to the test cases. But the code works fine without any issues for custom configurable menu, two way tree model binding. The two commits are in the same forked code.

**Usage :** 
 
```
{
  value: 'Prototype-based programming',
  settings: {
    'static': false,
    'rightMenu': true,
    'leftMenu': true,
    'cssClasses': {
      'expanded': 'fa fa-caret-down fa-lg',
      'collapsed': 'fa fa-caret-right fa-lg',
      'leaf': 'fa fa-lg',
      'empty': 'fa fa-caret-right disabled'
    },
    'templates': {
      'node': '<i class="fa fa-folder-o fa-lg"></i>',
      'leaf': '<i class="fa fa-file-o fa-lg"></i>',
      'leftMenu': '<i class="fa fa-navicon fa-lg"></i>'
    },
"menuItems": [
 {name:'New Model', action: 0, cssClassses: 'new-tag'},
{name: 'Custom Menu Item', action: 4, cssClasses:'custom-menu-item', execute: function(tree){
console.log(tree)}}
]
  },
  children: [
    {value: 'JavaScript'},
    {value: 'CoffeeScript'},
    {value: 'Lua'}
  ]
}
```

menuItems should be added to the each node settings and is of the type `NodeMenuItem[]` 
A execute field has been added to NodeMenuItem to add custom functions to a specific item.
```
export interface NodeMenuItem {
  name: string;
  action: NodeMenuItemAction;
  cssClass: string;
  execute?: any;
}
``` 

A Custom action is added to NodeMenuItemAction.
```
export enum NodeMenuItemAction {
  NewFolder,
  NewTag,
  Rename,
  Remove,
  Custom
}
```
action values - 0: New Folder, 1:  New Tag, 2: Rename, 3: Delete, 4: Custom

So If you want your custom function to be executed when you select a particular item in the menu, you will have give the action value as 4 and define your function as execute.
 `{name: 'Custom Menu Item', action: 4, cssClasses:'custom-menu-item', execute: function(tree){
console.log(tree)}}
`

If you want to rename a particular Menu item of the default menu, you should give it as 
` {name:'Renamed Menu Item', action: 0, cssClassses: 'new-tag'}`

**Note:**
'static' field in the settings should be false and either of leftMenu or rightMenu should be true for the customMenu to be visible.

Enjoy :+1:

**Comment by avadhootha** [comment]
Though what I wrote above works fine,  it seems to be a wrong to execute our custom function inside the code (ng2-tree). Also it causes losing the context of the component where it's being used. 
So I made changes appropriately to remove the execute in the NodeMenuItem Interface. Instead I am sending a menuItemSelected event with the selected node tree and selected item in the menu. So now you can execute the custom function by listening to this event(menuItemSelected) in the Component where this ng2-tree is being used.

**NodeMenuItem**
```
export interface NodeMenuItem {
  name: string;
  action: NodeMenuItemAction;
  cssClass: string;
}
```

**NodeMenuSelectedItemEvent**
```
export interface NodeMenuItemSelectedEvent {
  nodeMenuItemAction: NodeMenuItemAction;
  nodeMenuItemSelected?: string
}
```

Here are the commits [commit-1](https://github.com/avadhootha/ng2-tree/commit/ae9158aa1359375222cea6734952f0efa5a874ec) and [commit -2](https://github.com/avadhootha/ng2-tree/commit/1de417bf892ff9fe7e1cd8a53044977a8dc44b90)
Here is the [full code](https://github.com/avadhootha/ng2-tree). 
Here is how you should use it now.

Node Settings:
```
settings: {
    'static': false,
    'rightMenu': true,
    'leftMenu': true,
    'cssClasses': {
      'expanded': 'fa fa-caret-down fa-lg',
      'collapsed': 'fa fa-caret-right fa-lg',
      'leaf': 'fa fa-lg',
      'empty': 'fa fa-caret-right disabled'
    },
    'templates': {
      'node': '<i class="fa fa-folder-o fa-lg"></i>',
      'leaf': '<i class="fa fa-file-o fa-lg"></i>',
      'leftMenu': '<i class="fa fa-navicon fa-lg"></i>'
    },
   'menuItems': [
      {name:'New Model', action: 0, cssClass: 'new-tag'},
      {name: 'Custom Menu Item', action: 4, cssClass: 'custom-menu-item'}
   ]
  }
```

Action values are still the same.  0: New Folder, 1: New Tag, 2: Rename, 3: Delete, 4: Custom

As for the event, you should add an event handler for 'menuItemSelected' in the tree declaration like below.
<tree (menuItemSelected)="handleMenuItemSelect($event)"> </tree>

handleMenuItemSelect(e: MenuItemSelectedEvent) {
// Your code to be executed after clicking.
}
 (e)  in the above function will be something like this - MenuItemSelectedEvent {node: Tree, selectedItem: "New Model"}

**Comment by rychkog** [comment]
@avadhootha Thanks! Will have a look ASAP!
