### ISSUE TITLE
Expand node after setChildren

### ISSUE THREAD

**Issue by horsaco27** [valor-software/ng2-tree#251]
Hello.

Thank you very much for this compement!! It's so usefull.

My question.

I'm trying to expand a node after add children with a socket response.

```
public handleSelected(e: NodeEvent): void{
    const nodeController = this.treeComponent.getControllerByNodeId(e.node.id);
    let nuevosHijos: Array<TreeModel>;
    let padre: EspacioPadre = {espacio_padre_almacen_id: this.selectedAlmacen, espacio_padre_id: e.node.id};
    this.channelEspacio.push(ArbolAction.ObtenerHijos.valueOf(), padre)
      .receive("ok", ({hijos: res}) => {
        nuevosHijos = JSON.parse(JSON.stringify(res));
        nodeController.setChildren(nuevosHijos);
        console.log(res);
      })
      .receive("error", ({hijos: res}) => {
        console.log("Error al recbir hijos");
      });
    nodeController.expand();
  }
```

node not expand with nodeController.expand().

Thanks for reading.

**Comment by hotdog1987** [comment]
@horsaco27 try putting ```nodeController.expand();``` after ```nodeController.setChildren(nuevosHijos);``` and before ```console.log(res);```

**Comment by horsaco27** [comment]
Thank you for your answer, but still not working

**Comment by hotdog1987** [comment]
are you sure its ```e.node.id``` or ```e.node.node.id```? version i'm using ```ng2-tree@2.0.0-rc.8```

**Comment by horsaco27** [comment]
I'm ussing ng2-tree@2.0.0-rc.9 version.

You tree already has children? It seems tree without children can't expand. I trying to set children after click on one father.

Let me check your example...

**Comment by hotdog1987** [comment]
all the nodes in the tree that i work with, have at least an empty array as children.

**Comment by horsaco27** [comment]
Thank you for your help.

Your example not working for me. Code here.

```public handleSelected(e: NodeEvent): void{
    if (e && e.node && e.node.node && e.node.node.id) {
      console.log(e.node.node.id);
      console.log(e.node.id);
      const nodeController = this.treeComponent.getControllerByNodeId(e.node.node.id);
      console.log(nodeController.isCollapsed());
      
      if (nodeController.isCollapsed()) {
          nodeController.expand();
      }
    }
}
```
The result

![imagen](https://user-images.githubusercontent.com/20523765/38873049-74673ada-421a-11e8-84c7-290aaca4371e.png)

```e.node.id``` and ```e.node.node.id``` are the same

Every node has this struct: 

```
{ value: "Sección-7", id: 7, children: [] }
```

**Comment by hotdog1987** [comment]
I'm confused....```console.log(nodeController.isCollapsed());``` results ```false``` means it is expanded. Isn't that what you were looking for?

**Comment by hotdog1987** [comment]
If you don't mind, can you put your code in plunker, or [https://stackblitz.com/edit/angular?](https://stackblitz.com/edit/angular?)

**Comment by horsaco27** [comment]
The problem is that ```console.log(nodeController.isCollapsed());``` returns ```false``` but node is not expand. 

Here is the example:
https://angular-hazauh.stackblitz.io

I want to expand node whenever children are added.

**Comment by hotdog1987** [comment]
I see what the problem is...```children``` is an empty array. (my bad! I should have mentioned clearly before). It needs to be array of objects with empty values. Check this out:

``` 
public tree: TreeModel = {
    value: 'Programming languages by programming paradigm',
    id: 10,
    children: [
      {
        value: 'Object-oriented programming',
        id: 1,
        settings: {
            static: true,
            rightMenu: false,
            leftMenu: false,
            isCollapsedOnInit: true,
        },
        children: [{
            value: '',
            id: ''
        }]
      },
      {
        value: 'Prototype-based programming',
        id: 5,
        settings: {
            static: true,
            rightMenu: false,
            leftMenu: false,
            isCollapsedOnInit: true,
        },
        children: [{
            value: '',
            id: ''
        }]
      }
    ]
  };
```

It is advised to pass ```settings``` as well to make the nodes collapsed by default.

By the way, your ```if``` condition is incorrect. It should be ```e && e.node && e.node.node && e.node.node.id && e.node.node.id !== 10``` (make sure that your logic runs only on child nodes not on root)

**Comment by horsaco27** [comment]
That's the idea!

Thak you very much! Now working perfectly!!

Leave this here if anyone needs help!

https://stackblitz.com/edit/angular-hazauh

**Comment by ramesh437** [comment]
when I created two buttons when I clicked new file button it added a new file and click new folder button added folder also but the problem is when I added a folder and then added child then it's not collapsed and expanded please tell me the solution.here is the code and my problem.
https://stackblitz.com/edit/ng2-tree-create-file-4yrdcm?file=app/hello.component.ts
