### ISSUE TITLE
Install from github repository

### ISSUE THREAD

**Issue by lovery** [valor-software/ng2-tree#29]
Hello,
I'm trying to install the package from a repository and notice that in .gitignore there are compiling files such as: .js, .d.ts and bundles which are ignored from the repository.
Notice also that there is a .npmignore which ignores the all *.ts and the *.js.map in the root directory.
Is there a way to install the package for a repository without dealing with ...ignore files?

**Comment by rychkog** [comment]
@lovery If I exclude them from .gitignore then those files that are build artifacts, might be accidentally committed to the repo. You can use alpha version `1.0.1-alpha.1` for now. It has the latest changes.

According .npmignore - I've included those files in there cause don't want them to be published in npm.

If you have an idea on how to deal with this - please, let me know.
