### ISSUE TITLE
Error when implementing ng2-tree  Observable

### ISSUE THREAD

**Issue by medmedchiheb** [valor-software/ng2-tree#316]
i encounter  a probelm when i integrate ng2-tree
the probelm is "ERROR TypeError: Observable_1.Observable.of is not a function"
as i can see the rxjs of this library should update to 6 to support new angular 6

**Comment by acejiyu** [comment]
I also had the same problems.
Using the latest version, I tried to change the `var Observable_1 = require("rxjs/Observable")` to `var Observable_1 = require("rxjs")`,the problem can be solved.

**Comment by medmedchiheb** [comment]
yes and the authors of this library does not respond for a long time,
i recommend everyone to take a look at this https://github.com/cybercomet/ngx-nestable
