### ISSUE TITLE
Error on importing Tree Module - possible duplicate

### ISSUE THREAD

**Issue by danielcooke1996** [valor-software/ng2-tree#33]
Hi there,

I'm receiving a problem with angular upon compiling with the Tree Module import.

The error reads: 

TypeError: ctorParameters.map is not a function
	    etc. etc.

This is because when the angular compiler evaluates the ctorParamaters for TreeService(), it is defined as an anonymous function - see attached image

![image](https://cloud.githubusercontent.com/assets/22816887/21679400/ca97a3da-d33b-11e6-8a8c-ca9679bf7433.png)

Now I'm not sure if this is a problem on my end or with the ng2-tree, but its a strange one. I had the ng2-tree working before the new year.

Any input would be highly appreciated.

Thanks

**Comment by rychkog** [comment]
@danielcooke1996 Which version of the tree do you have installed in your node_modules?

**Comment by danielcooke1996** [comment]
Okay so its much too early in the morning for this - I had identified the problem unkowningly.

> I had the ng2-tree working before the new year.

The problem arose from an incompatible version of angular that is necessary for my project. I fixed it by specifying version 1.0.0 in package.json

This issue can be closed.
