### ISSUE TITLE
ngc can't build with npm installed version

### ISSUE THREAD

**Issue by netsesame2** [valor-software/ng2-tree#36]
I've an ionic2 project, and install your ng2-tree by npm install, all will be fine without ngc. If turn on using ngc, build will fail throw following:

can't resolve module ./draggable/node-draggable.directive from E:/My Projects/App/ErrorBookApp2/node_modules
/ng2-tree/src/tree.module.d.ts

The reason is the tree.module.d.ts file has been trimed all import parts as:
export declare class TreeModule {
}

I can only add these import references which copy from your git source tree.moudel.ts, it works:
import { NgModule } from '@angular/core';
import { TreeComponent, TreeInternalComponent } from './tree.component';
import { CommonModule } from '@angular/common';
import { NodeDraggableDirective } from './draggable/node-draggable.directive';
import { NodeDraggableService } from './draggable/node-draggable.service';
import { NodeEditableDirective } from './editable/node-editable.directive';
import { NodeMenuComponent } from './menu/node-menu.component';
import { NodeMenuService } from './menu/node-menu.service';
import { TreeService } from './tree.service';

export declare class TreeModule {
}

So, it is only a temp way. Hope to resolve.

**Comment by rychkog** [comment]
@netsesame2 Please, provide ng2-tree version that you use (also angular version and typescript version)

**Comment by netsesame2** [comment]
ng2-tree: version: '2.0.0-alpha.0'
angular version: @angular/core@2.2.1
typescript version: 2.0.9

**Comment by rychkog** [comment]
@netsesame2 have you tried latest stable angular? Cause ng2-tree of this version was built with angular 2.4.1

**Comment by netsesame2** [comment]
Oh, sounds right. The angular I use is an embedded version in Ionic2. So, to say, I can't try it's latest version. Maybe it is the bug lived in the old version, no idea.

And, another question, by the way. I tried your tree this day, and found that no way to call it's internal API, such as expand, collapse, etc. It is not convenient when I want to apply it on mobile App. In addition, it will be more well if there a built-in css definition.

**Comment by rychkog** [comment]
@netsesame2 according icons customizations - there is a PR from @lovery (also awaiting tests that I need to finish before merging). If you want to override some styles than you can do it in version '2.0.0-alpha.0' cause styles in there distributed as separate file. If it won't help then we have a bug :)

Also according API that will allow to collapse, expand tree etc - could you create an issue for this?

**Comment by netsesame2** [comment]
Sorry for not find any css file in the git version. Did  you mean the demo page?

As on mobile app, no mouse  and keyboard there, so need some way to expand, collapse and drag the node by finger. So said API, is the scene where can finish the job well, that's it.

**Comment by rychkog** [comment]
@netsesame2 
Here is the css - https://github.com/valor-software/ng2-tree/blob/develop/src/styles.css

And here is the separate demo project (created via angular-cli). Css file included there in here
https://github.com/rychkog/ng2-tree-demo/blob/master/angular-cli.json#L22

I understand your issue with mobile devices - will add this to ng2-tree todo (https://github.com/valor-software/ng2-tree/issues/37). It would be great if you could add there more details about what kind of API (it should be folding, expanding, dragging or something in addition to those) do you need exactly in your usecase. It will help me to think of it in a more clear way.
