### ISSUE TITLE
Implement API for folding, expanding, dragging node etc.

### ISSUE THREAD

**Issue by rychkog** [valor-software/ng2-tree#37]

**Comment by lovery** [comment]
Hello @rychkog,
I manage to finish most of my other tasks and I'm thinking to make this API, but I'm not sure how to implement it.
I will think about it, but if you have an idea how this should be done it will be nice to share it :)

**Comment by rychkog** [comment]
Great! :)

@lovery In order to implement this, we most probably have to expose internal model (Tree class) to the client's code. Then this exposed tree can have public API for `tree.collapse()`, `tree.expand()`. According to drag-n-drop - it is a bit more complex comparing to collapse, expand: as a first approximation it might look like `tree.moveTo(otherTree)`. 

The main reason behind this is to make a tree a bit more mobile-friendly, so that when some of the events are missing on mobile devices - users can manage tree via API.

Also maybe you have in mind some other features that can be exposed via API? 

Here is [a little dump of my thoughts](https://github.com/valor-software/ng2-tree/blob/develop/TODO.md) on this topic as well as on some others tree enhancements :)

**Comment by rychkog** [comment]
Put your thoughts in here - we'll discuss all the stuff :)

**Comment by lovery** [comment]
@rychkog I agree that drag-n-drop is a bit complex. I was thinking to start with expand and collapse.

The reason I need this API is because on my page I have other elements which are connected to the tree, so I need a way to manipulate the tree from outside.

I was thinking also for a selecting a node via this API.

About the tree class I'm not sure that this is the best option, because at the moment in this class there are so many public methods and if we give an access from outside to all those methods users can mess up things. Also I can't imagine how we're going to give access to this class at the moment.

I'm thinking about a new property in TreeModel which will give access to manipulate a particular node. This way the user will have access to the API without any major changes.

What do you thing about this?

**Comment by rychkog** [comment]
> I'm thinking about a new property in TreeModel which will give access to manipulate a particular node

@lovery Can you elaborate this via quick pseudo code example?

> About the tree class I'm not sure that this is the best option

Agree. Also, we can expose a special class smth like TreeController to the user that will encapsulate a tree inside itself (basically wrapper for the tree) and will provide a required interface without exposing full tree API.

> I was thinking also for a selecting a node via this API.

Yes, in order to collapse, expand and so on we should be able to easily acquire any node from the tree
So should have smth like `tree.find(predicateFunction)`

**Comment by lovery** [comment]
May be something like this:
```
export interface TreeModel {
  value: string | RenamableNode;
  id?: string | number;
  children?: TreeModel[];
  loadChildren?: ChildrenLoadingFunction;
  settings?: TreeModelSettings;
  api?: API;
  _status?: TreeStatus;
  _foldingType?: FoldingType;
}

export interface API {
  select: Function;
  collapse: Function;
  expand: Function;
}
```
If the API is a global class we will need this find function, but it can became very slow for big trees.

**Comment by rychkog** [comment]
This is a bit confusing, cause TreeModel describes configurable by user properties and is used as a *model* for Tree class. Using this approach it also will be responsible for API..

**Comment by lovery** [comment]
May be it's a bit confusing.
The other approach is a find function, but there is this problem with the speed.
It has to scan the whole tree in the worst case, which is O(n) if there are n nodes.

**Comment by rychkog** [comment]
@lovery What if we'll create a dictionary, where every key is a node.id and value is a node itself?
pros: 
 - O(1)
 - easy to implement

cons:
- id field should be required
- additional memory needed for storing dictionary
- the dictionary should be always in sync with tree
- we need to come up where to keep the dictionary

Tradeoff in unavoidable - we can have fast but with increased memory consumption or slower but with no extra memory consumption

**Comment by lovery** [comment]
My suggestion was to leave this decision to the user.
In fact I was planning to make this dictionary in my app, but if it is in the tree itself is also ok for me.

In fact I it is possible to searching for a node in a tree by it's parents. If the user knows all nodes to a particular node it can get the node quite fast without extra memory.

May be it is possible to implement all options and make it possible for user to choose - this will be quite big and complicate change :)

**Comment by lovery** [comment]
@rychkog I've just managed to make a basic collapse/expand and select of a node methods.
I've made a class TreeAPI, an attach it to TreeService, so it can be accessed from everywhere.
The api uses the TreeInternalComponent for now, because all functions I needed to call ware there.
I will create a pull request so you can easily see my changes.

If you it is ok I can continue with README and tests.

**Comment by rychkog** [comment]
@lovery Sorry, that disappeared - had lots of work.

I think that getting the API via event is a bit unusual way of doing this. API is a way to control something, not an event from an interaction with a tree. But we are going in a right direction.
What if each InternalTreeComponent will have public method getTreeController, which is supposed to provide an instance of the class responsible for handling all the interaction events in TreeInternalComponent itself, therefore we will give user controller for manual management, and this controller, in turn, is used by our component as well.  Each TreeController will have a reference to its TreeInternalComponent (like it is in your PR with API class) apart from that each component will have  getChildControllerById method which is able to search for a child and return its controller. What do you think?

**Comment by lovery** [comment]
Hi @rychkog 
I agree about getting the API via event.
About your suggestion I'm not sure that I get your idea right, please take a look at the updated PR and let me know what do you think.

I've also added two new methods for collapsing and expanding a node and change the select method to select a node only if it isn't already selected.

**Comment by rychkog** [comment]
@lovery I've had a quick look - it is almost thing that I have in mind :) Will elaborate on this in the evening - have a ton of work now :)
