### ISSUE TITLE
Tree animation

### ISSUE THREAD

**Issue by pablanco** [valor-software/ng2-tree#38]
Hi @rychkog! I was able to install the component in my project, I can see the demo tree and capture click events over the items. 

![captura de pantalla de 2017-01-17 11-24-17](https://cloud.githubusercontent.com/assets/3788239/22024101/9703bc32-dca7-11e6-9440-7d195a8a9668.png)

The thing is that I can not close or open the structure like the [demo](http://valor-software.com/ng2-tree/) do. I'm not getting any error on the browser console. 

@angular/core@2.4.3
ng2-tree@2.0.0-alpha.0

Could you advice please?
Thanks!

**Comment by rychkog** [comment]
@pablanco I've extracted styles into separate file and now they should be included in your html or by your build tool (documentation available is not up to date with 2.0.0-alpha.0)

Please, have a look at this project which is built with angular-cli 
https://github.com/rychkog/ng2-tree-demo
Especially at the place where styles are included https://github.com/rychkog/ng2-tree-demo/blob/master/angular-cli.json#L22.

Also in the demo given in the actual ng2-tree repo you can find this line https://github.com/valor-software/ng2-tree/blob/develop/demo/app.component.ts#L4 which does exactly the same thing - includes styles.

**Comment by pablanco** [comment]
@rychkog I have the styles included already and still not working, this may be not the problem ...

**Comment by bocao9107** [comment]
I have the same problem

**Comment by rychkog** [comment]
@pablanco @bocao9107 I've updated this demo repo (https://github.com/rychkog/ng2-tree-demo) to the angular 2.4.3 and angular-cli 1.0.0-beta.25.5. Cannot reproduce issue in there - tree works.

In order to resolve your issue I need a way to reproduce it. Can you give me "Hello world!" project where this issue is reproducible?

**Comment by bocao9107** [comment]
@rychkog @pablanco After I add style into .json, everything just start working. Thanks guys
