### ISSUE TITLE
Show multiple parent nodes

### ISSUE THREAD

**Issue by tusharparmar** [valor-software/ng2-tree#40]
I am unable to do 2 things,
1)  show multiple top parent nodes, right now it is showing only one top parent node at a time.
2) add icon for each node, like i hvae admin, child user, all will have different icons. 

can you help me in doing this??

**Comment by tusharparmar** [comment]
did both thing by changeing its code. no need to do this now.

**Comment by rychkog** [comment]
@tusharparmar Can you tell me a bit more about multiple parents? You just want to hide a root and still having direct children visible? If so there is an upcoming update already in a develop branch

**Comment by tusharparmar** [comment]
Yes thats what is am asking fior, so that i can have multiple parents at top lavel, currently its only one.

also if you can include events and suggestion for below in upcoming developments, that would be great:

1) add parameter for each node like "hasChild" with value true/false or 1/0 [whay required: it will allow to setup dynamic data loading for tree. if you are getting fdata from a service, service will just pass hasChild to true/1 and based on that tree will decide to show or not show arrow with node.]

2) click event of arrow for parent node [whay required: when you want to load dynamic data, on click of the arrow, you can call to service for childs of selected parent]

3) allow to add dynamic class with each tree node which will be used for setting icons as for each node based on attached class with it.

**Comment by rychkog** [comment]
@tusharparmar Some of those features should come from https://github.com/valor-software/ng2-tree/pull/34 (like 3rd one)
1st feature is in develop branch and is implemented on top of the new abstraction called `Tree`
2rd one I will add to my TODO list.

**Comment by tusharparmar** [comment]
thank you rychkog,

let me know if i can help you somewhere.
