### ISSUE TITLE
Task 'build' is not in your gulpfile

### ISSUE THREAD

**Issue by peterennis** [valor-software/ng2-tree#41]
Windows 10
Download master
npm install && gulp build

I get the error above.
How do I build and run the demo so I can test this?
I could not find a simple getting started doc.

![capture004](https://cloud.githubusercontent.com/assets/140737/22668948/73025390-ec77-11e6-830d-1c4c0cf3c0d3.png)

**Comment by rychkog** [comment]
@peterennis Thanks for this! In couple days will make an update for ng2-tree - this will be resolved. Though there is no developer doc for ng2-tree - you are right need to write it.

**Comment by peterennis** [comment]
Let me know when it is ready to test. I can document my work on W10 as I try using it and create issues if I get stuck.

**Comment by rychkog** [comment]
@peterennis Thanks! You can check the latest develop branch. All the changes are in there. Gulp is not used for ng2-tree building, hence there is no need to run `gulp build`. It is though used for deploying ng2-tree to github pages.
Please have a look at **scripts** section in https://github.com/valor-software/ng2-tree/blob/develop/package.json
