### ISSUE TITLE
tree data with REST API Call

### ISSUE THREAD

**Issue by nitslucky** [valor-software/ng2-tree#45]
Hi, 

Is it possible to produce such kind of tree with REST API data? The first call should load all the root nodes like the image here:
![firstcall](https://cloud.githubusercontent.com/assets/23555070/22835517/5c1ddc54-efb9-11e6-98fa-742007d0050c.PNG)

And then children should be loaded with another call to REST API when i click on plus icon for example the image given below:

![getchildren](https://cloud.githubusercontent.com/assets/23555070/22835516/5c1b757c-efb9-11e6-8cd8-82d0b99176cd.PNG)

**Comment by rychkog** [comment]
@nitslucky Hello, no currently there is no API for that. But this feature is on TODO list for the ng2-tree@2.0.0-alpha.4

**Comment by chuihinwai** [comment]
Is there a workaround right now? For example, have the tree "collapsed" by default, and listen to the click events on the "expand" buttons?

**Comment by rychkog** [comment]
@chuihinwai It is by default expanded, but in general it should be possible to do this in that way. But we don't have `expand` events propagated.

**Comment by chuihinwai** [comment]
So is there anything I can do as a workaround for now? Thanks!

**Comment by rychkog** [comment]
@chuihinwai I don't see a workaround for lazy loading via current implementation

**Comment by rychkog** [comment]
@chuihinwai, @nitslucky I've implemented async children in latest version https://www.npmjs.com/package/ng2-tree#load-children-asynchronously

Give it a try
