### ISSUE TITLE
css

### ISSUE THREAD

**Issue by eddy2enam** [valor-software/ng2-tree#46]
Hi...
i like to overide css,
when do rename... i like to make width more longer
how to do that??

thx

**Comment by rychkog** [comment]
@eddy2enam Do you use AngularCLI in your project? How do you include styles in your project?

**Comment by eddy2enam** [comment]
i add to to angular cli

"styles": [
        "styles.css",
        "../node_modules/ng2-tree/src/styles.css"
      ],

i try to play around with /node_modules/ng2-tree/src/styles.css 
![2017-02-13-tree](https://cloud.githubusercontent.com/assets/25707662/22877083/510ad2fa-f206-11e6-9e98-b51df8426631.png)

thx

**Comment by rychkog** [comment]
@eddy2enam Just try to include your styles after ng2-tree styles, like

```css
"styles": [
    "../node_modules/ng2-tree/src/styles.css",
    "styles.css",
]
```

Then in your `styles.css` you can override classes that you are interested in. In you particular case you should override `tree input.node-value` (play a bit with css  specificity if this won't be enough to get to this element)
