### ISSUE TITLE
create custom template and  display confirm before delete from tree

### ISSUE THREAD

**Issue by hatemalhassani** [valor-software/ng2-tree#48]
how to create custom template for tree including create new folder or item? 

and 

how to display confirm before delete from tree?

thanks

**Comment by rychkog** [comment]
Hi @hatemalhassani 
1) There is no way to create a custom template but you can override styles (`node_modules/ng2-tree/styles.css`)
2) There is no way to display confirm before tree (node) removal :( . But this is a good idea and I will add this feature to the backlog

**Comment by hatemalhassani** [comment]
thank you for your reply @rychkog 

for custom template:  I think this feature is vrey usefull for me  because i need  to i add custom form (to add new object insead of value of string).

**Comment by rychkog** [comment]
@hatemalhassani I see, so in your usecase you want to provide html as node values. Will think about it - maybe will manage to bring this to the tree as well

**Comment by hatemalhassani** [comment]
in my case i use value of object "*RenamableNode*" so i need to create item with multi-value (custom template for add new item)
