### ISSUE TITLE
404 Error when instalation

### ISSUE THREAD

**Issue by quindimildev** [valor-software/ng2-tree#5]
I have followed the how-to tutorial, but when I use TreeComponent I get an 404 error, I am not able to run my app. 
I am using the last angular version. (RC4)
I have used also this config without success: 

```
    var map = {
...
        'ng2-tree':                   'node_modules/ng2-tree',
        'lodash':                   'node_modules/lodash'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
...
        'ng2-tree':                   { main: 'index.js', defaultExtension: 'js' },
        'lodash':                   { main: 'index.js', defaultExtension: 'js' }
    };
```

Here is the stackoverflow question with further info: [http://stackoverflow.com/questions/38825062/ng2-tree-module-not-found-after-install-on-an-angular-2-new-app](http://stackoverflow.com/questions/38825062/ng2-tree-module-not-found-after-install-on-an-angular-2-new-app)

**Comment by quindimildev** [comment]
I have a workaround modifying the classes, adding the moduleId to each component. Cause the relative path was not working.

**Comment by rychkog** [comment]
@quindimildev, thanks for pointing me to this issue.
Hm, that's because I've implemented this with webpack in mind... Need to test this for System.js as well..

**Comment by rychkog** [comment]
Now ng2-tree is bundled with build for system.js as well
