### ISSUE TITLE
Css for selected node

### ISSUE THREAD

**Issue by vinhphamduc** [valor-software/ng2-tree#51]
Hi guys,
I'm beginner of Angular2. I using ng2-tree in our project, and i want highlight selected node. How to implement it?
Thanks for support,

**Comment by rychkog** [comment]
@vinhphamduc In your CSS you should override `.tree .node-selected` and `.tree .node-selected:after` (this one is responsible for underline in the default styles)
https://github.com/valor-software/ng2-tree/blob/master/src/styles.css#L106
