### ISSUE TITLE
How to add systemjs seed?

### ISSUE THREAD

**Issue by KhizarJaved** [valor-software/ng2-tree#52]
![ng2-tree-errors](https://cloud.githubusercontent.com/assets/16715379/23342565/cbd5abae-fc7e-11e6-880b-8f639a0d8b14.PNG)

**Comment by rychkog** [comment]
@KhizarJaved I will try to create a repo with this - will notify you once it is ready

**Comment by KhizarJaved** [comment]
I have fixed this issue by adding 
, 'ng2-tree': "npm:ng2-tree"
,'lodash':"npm:lodash/lodash.js"

in a map object and also adding these lines

'ng2-tree': {
                main: 'index.js',
                defaultExtension: 'js'
            }  
in  a packages object of system.config.js
