### ISSUE TITLE
HTML tag in TreeModel value not showing properly

### ISSUE THREAD

**Issue by cleanyong** [valor-software/ng2-tree#57]
I think this issue maybe related to ng2-tree escapes html tag.

Here is what I want to do:
* get a JSON generated with backend API
* render the HTML tag in JSON response in ng2-tree

But this issue is not rendering:
```
<a href="/static/logs/a00915772862111eb3a13595abe27ee6f495891a.log">a00915772862111eb3a13595abe27ee6f495891a.log</a> 
```

**Comment by rychkog** [comment]
@cleanyong I see, will have a look

**Comment by cleanyong** [comment]
Tree.ts  line 305 has typo:
```
   * @returns {boolan} - A flag indicating whether given value is Renamable node or not.
```

boolan should be boolean

**Comment by Prasadrvs** [comment]
I am also facing same issue.. can you please help us ASAP

**Comment by rychkog** [comment]
@Prasadrvs @cleanyong This is already implemented in the latest version on npm - please, give it a try
