### ISSUE TITLE
Systemjs configuration

### ISSUE THREAD

**Issue by vinhphamduc** [valor-software/ng2-tree#58]
Hi,

I try using ng2-tree and configuration systemjs below:
'ng2-tree'                  :   'npm:ng2-tree',
'lodash'                    :   'npm:lodash'

'ng2-tree'                  :   { main: './index.js', defaultExtension: 'js' },
'lodash'                    :   { main: './index.js', defaultExtension:'js' }

or
'ng2-tree'                  :   'npm:ng2-tree',
'lodash'                    :   'npm:lodash/lodash.js'

'ng2-tree'                  :   { main: './index.js', defaultExtension: 'js' },

but it not working.

Thanks,

**Comment by rychkog** [comment]
@vinhphamduc Please, have a look at https://github.com/valor-software/ng2-tree/issues/52

**Comment by vinhphamduc** [comment]
@rychkog I try setting with
var map = {
        'app'                       :   './dist',
        '@angular'                  :   'npm:@angular',
        'angular-in-memory-web-api' :   'npm:angular-in-memory-web-api',
        'rxjs'                      :   'npm:rxjs',
        'ng2-tree'                  :   'npm:ng2-tree',
        'lodash'                    :   'npm:lodash/lodash.js'
    };

and
var packages = {
        'app'                       :   { main: './main.js', defaultExtension: 'js' },
        'angular-in-memory-web-api' :   { main: './index.js', defaultExtension: 'js' },
        'rxjs'                      :   { defaultExtension: 'js' },
        'ng2-tree'                  :   { main: './index.js', defaultExtension: 'js' },
    };
but it not working

**Comment by rychkog** [comment]
@vinhphamduc Does it work without ng2-tree? Cause there was a change in rxjs configuration as well as far as remember

**Comment by vinhphamduc** [comment]
@rychkog Yes, it work without ng2-tree, and i use rxjs@^5.0.1

**Comment by tamilmca2006** [comment]
After installing your package in my project  i am getting the template parse error. I have attached screenshot for that pls check and let me know.

for your reference see the systemjs.config.js - code 
`/**
 * System configuration 
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            'angular-tree-component': 'node_modules/angular-tree-component/dist/angular-tree-component.umd.js',
            '@angular/http/testing': 'npm:@angular/http/bundles/http-testing.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            'angular2-tree-component':'npm:angular2-tree-component',

            // other libraries
            'rxjs': 'npm:rxjs',
			'ng2-tree': "npm:ng2-tree",
			'lodash':"npm:lodash/lodash.js"			
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            'rxjs': {
				main: '/bundles/Rx.js',
                defaultExtension: 'js'
            },
			'ng2-tree': {
			main: 'index.js',
			defaultExtension: 'js'
			}
        }
    });
})(this);
`

![angular-tree-error](https://cloud.githubusercontent.com/assets/5584168/25329925/5ae59d38-28fb-11e7-8a2a-400c7dd886d2.png)

**Comment by rychkog** [comment]
@vinhphamduc Have you resolve your issue? Otherwise you can try to use latest ng2-tree published on npm
