### ISSUE TITLE
Collapse current node when on selected

### ISSUE THREAD

**Issue by MstfTkrsln** [valor-software/ng2-tree#61]
Hi,

I couldn't find the API function for following scenario.

How to collapse the current node in `onNodeSelected(e: NodeEvent)` event?

Thanks.

**Comment by rychkog** [comment]
@MstfTkrsln There is no such an API - but it is one of the features that will be released in the next alpha version

**Comment by rychkog** [comment]
@MstfTkrsln Now you can - please, have a look at https://github.com/valor-software/ng2-tree#gun-controller
