### ISSUE TITLE
[question/enhancement] Update node value with action outside of the tree

### ISSUE THREAD

**Issue by andlambert** [valor-software/ng2-tree#62]
Hello,

Is it possible to update a node value, without reloading the entire tree component with an action outside of the tree?

For example, I want to load a tree at start with only the first 10 node values filled, others are empty. Then, I want to fill the nodes values on user scroll. 
This is mandatory in my case because the node content are filled with data with the return of an API call and they might be lots of nodes (up to 3k, so it is not possible to load everything at start and to reload the tree after each scroll).

Thanks for you answer and your time!

**Comment by rychkog** [comment]
@andlambert Sorry for a late response. Will [async children loading](https://github.com/valor-software/ng2-tree#load-children-asynchronously) resolve your issue? And if it won't - let's elaborate this further

**Comment by andlambert** [comment]
Hello, Thanks for the response.
Unless I am missing something here, I think it might not solve my problems.

Indeed, what I want to do is to load children on user scroll and not all at start (even async). 
Let's assume I have 3k children in my tree, I want to show the first let's say 50 on screen. On scroll, I want to load the next 50, and so on. 
Loading 3k, even async, would load too much maybe useless data and consumes lots of bandwith.

My idea was to load the tree entirely, with empty children and then update the 'necessary' ones with corresponding data on user scroll event.

However, maybe it's a too specific use case.

**Comment by rychkog** [comment]
@andlambert Ok, say you have a tree
A
|----B
|----C
D
|----E
|----F

On first load you want to load only __A__ with its children, then on scroll event - __D__ and its children, right?

**Comment by andlambert** [comment]
That's a solution, if it is possible without reloading the entire component (if the tree is huge, to avoid to recompute all DOM).

My idea was:
1) First load all the tree, B and C filled with Data, E and F empty. 
2) on scroll event, fill E and F.
But maybe your idea is better

**Comment by rychkog** [comment]
@andlambert Please, let me know, whether you've managed to make it work

**Comment by andlambert** [comment]
Ok I will let you know if I manage to do something nice, thanks for your time.
