### ISSUE TITLE
Select the same node when reloading/routing to tree component

### ISSUE THREAD

**Issue by devdcores** [valor-software/ng2-tree#63]
Hi

Currently i am using ng2-tree like this.

i made two div in the page, left div have this tree structure, right side i will load component depending on selected treenode.

The issue is, when i click on treenode, right div is loaded with component. now if i reload the page, in the left div the selected treenode is not highlighted/selected. whereas in the right div is with that component.

pic: before page reload
![before reload](https://cloud.githubusercontent.com/assets/14878408/23939542/2668e904-0987-11e7-8089-45904a6d2ff3.JPG)

so is there any way programatically select/click the treenode, so that when page reloads it automatically selects/highlights the treenode.
 
pic: after page reload(india is not selected/highlighted in the tree)
![after reload](https://cloud.githubusercontent.com/assets/14878408/23939566/50335f4e-0987-11e7-954e-c390a9d18375.JPG)

**Comment by rychkog** [comment]
@devdcores I'll have a look as soon as possible. Will let you know once find something

**Comment by devdcores** [comment]
@rychkog Thanks for your reply. It would be really helpful if u find something in this regard.
In my current application i am using your tree in many pages. when we navigate from one page to other the tree is again initialized and no selected item will be there. 
is there any way we can save the tree state (opened nodes, selected item). so that we can restore the state of the tree. when navigating between the pages.

**Comment by igasparetto** [comment]
Isn't there an option to flag an element as selected in the data?

**Comment by rychkog** [comment]
@devdcores @igasparetto This new API should help you with your issue
https://github.com/valor-software/ng2-tree#gun-controller

**Comment by roydekleijn** [comment]
How can we automatically expand the tree once selecting a node ?

**Comment by rychkog** [comment]
@roydekleijn Could, you reproduce the issue with null instead of treeController using stackblitz.com?
This way I'll be able to help you ASAP.

**Comment by roydekleijn** [comment]
https://stackblitz.com/edit/angular-cptwup


I want the tree to be opened to node 7 (in this case)
