### ISSUE TITLE
Assign an id to a node

### ISSUE THREAD

**Issue by Maquiavelo1408** [valor-software/ng2-tree#67]
How to make a node have an id and thus be able to identify it?

**Comment by rychkog** [comment]
@Maquiavelo1408 It is already [in development](https://github.com/valor-software/ng2-tree/tree/develop#tree-1) - will be available with the nearest release.
For now, there [is a workaround](https://github.com/valor-software/ng2-tree/issues/6)

**Comment by Maquiavelo1408** [comment]
Thanks for answer, i'll waiting for the release.

**Comment by rychkog** [comment]
@Maquiavelo1408 In the new version of the tree (check it out on npm) this is already available
