### ISSUE TITLE
Use a different model instead of TreeModel

### ISSUE THREAD

**Issue by AlienWareSumant** [valor-software/ng2-tree#69]
I have a tree whose model is not same as defined in TreeModel (installed ng2-tree by bower). Can I use a different model to render the tree instead of the default one.

**Comment by rychkog** [comment]
@AlienWareSumant you should transform your model into `TreeModel`

**Comment by AlienWareSumant** [comment]
If I change the treemodel in tree.types.d.ts then that would become excluded at the time of deployment as bower will pull the initial version again. @rychkog

**Comment by rychkog** [comment]
@AlienWareSumant you shouldn't change build. You just need to transform your object into the object that conforms to `TreeModel` interface (have the same structure).
