### ISSUE TITLE
Move angular to peerDependencies

### ISSUE THREAD

**Issue by nnixaa** [valor-software/ng2-tree#7]
Hey Guys,

Thanks for the module.
I'm currently moving our ng2-admin (which uses this package) to angular rc.5 and one thing is blocking us from moving the tree component is that it has angular rc.4 in the **dependencies** section instead of **peerDependencies**.
This causes npm to install angular rc.4 in its own folder under the tree module.
In its turn, this causes a known issue (http://stackoverflow.com/a/35978010) when angular throws the 'No Directive annotation found on *Component' exception.

Thanks and looking forward to your response.

**Comment by hoswey** [comment]
vote+1

**Comment by homofortis** [comment]
+1

**Comment by nick-wellinghoff-sp** [comment]
+1

**Comment by rychkog** [comment]
@nnixaa I see. Will move angular from dependencies to peerDependencies

**Comment by rychkog** [comment]
@nnixaa, I've moved dependencies to devDependencies and module doesn't have dependencies section anymore. So it should resolve your issue I hope
