### ISSUE TITLE
Question : Can i add a lead Node in to the tree Dynamically?

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-tree#72]
Usecase: 

I wanted to add a leaf node[Programmatic way] on a button click.

In my Application, I don't need right click on the tree to add a leaftNode. I need to add a leaf Node under particular branch, on button click.

   `public tree: TreeModel = {
        value: 'OAM',
        settings: {
            'static': true
        },
        children: [
            {
                value: 'Conf',
                children: []
            },
            {
                value: 'Stats',
                children: []
            }
        ]
    };`

At first the Children will be Empty, on button click, i need to add children under a particular branch.
I will get, on which branch i need to add child.

can it be achieved?

**Comment by rychkog** [comment]
@Rakesh-Harsha Fair usecase, but currently you cannot do it. Will have a look how to elaborate it and onboard to the tree...

**Comment by Rakesh-Harsha** [comment]
Okay, Thank you.

Looking forward for the changes.

**Comment by rychkog** [comment]
@Rakesh-Harsha Please, have a look at the https://github.com/valor-software/ng2-tree#gun-controller, this should help you
