### ISSUE TITLE
LoadChildren Problem

### ISSUE THREAD

**Issue by PMoransais** [valor-software/ng2-tree#73]
I am playing with your tree. I have several suggestions and a question

1) You provide an interface to add and delete nodes. 
          
There is no flexibility as to the actions that are permitted. It is not possible to allow creation and       disallow delete. It is an all or nothing! This really needs to be implemented.

To make matters worse, there is no programmatic way to add or delete nodes. This capability should be provided with functions so that your users can provide their own interface. I did not try to alter the input node to see if the tree is responsive to data changes. If is not, at present is the only way is to reload the tree in its entirety? That would not be good.

2) there is no concept of selection
You provide a selected event passing it the selected node but there is no way to programmatically select a node in the tree (that I could find). Since you mandate the format of the nodes, you could consider adding a selected property?

3) the loadChildren functionality
The doc is not clear. You should describe that the value of the field loadChildren in the node object must be either the name of a 'loading function' ( or an anonymous function) designed to load the nodes that will be added to the tree. That loading function is called by the tree and passed as a parameter a callback function. The 'loading function must then call the callback function with an array of node objects.

Aside from the lack of clarity, this mechanism does not provide any information about the requesting node that will contain the new nodes as children. Thus, each node must receive a different Loading Function. It would be better to allow for scenarios where a unique loading function can intelligently provide the requested nodes because it knowns which node makes the request

Now to my question: after a call to the callback function provided in my loading function I am able to provide nodes and they show properly in the tree. However, the parent node shows a 'loading...' caption which stays after the load of the children load is completed. I do not know how to remove it

Thanks

Philippe Moransais

**Comment by rychkog** [comment]
@PMoransais Let's start first with your qestion - once resolved - I will respond to your suggestions.

> Now to my question: after a call to the callback function provided in my loading function I am able to provide nodes and they show properly in the tree. However, the parent node shows a 'loading...' caption which stays after 
> the load of the children load is completed. I do not know how to remove it

Please, give me steps to reproduce this behavior on [demo example](https://github.com/valor-software/ng2-tree/tree/develop/demo) (chunks of code are welcomed)

**Comment by PMoransais** [comment]
@rychkog 

I resolved that question but did not get a chance to post this morning. It was my fault. 

After looking at the problem closely, I realized that the "Loading..." text was provided by a CSS style.
This stopped working because I modified the CSS highlighting of nodes to provide for a more classic highlight without animation, and probably messed up thinks where the loading text was never removed.
Being short on time, I just removed the loading style altogether, even-though it is a nice touch.
Perhaps you could document how the CSS can be safely modified to accommodate a more classic look and highlighting.

I am looking forward to read your comments

**Comment by vaibhav-rbs** [comment]
Hi,
I am having similar issue described by some users regarding using loadChildren attribute, 

we are using loadChildren as following, following code is written in form-explorer.components.ts file.
```

import {TreeModel, NodeEvent} from 'ng2-tree';

import {EntityFormService} from '../../services/entity-form.service';

...snip...


  ngOnInit() {
    this.tree = {
      value: this.config.initial,
      // children: this.entityFormService.getFilesystemListdir(this.config.initial),
      loadChildren: (callback) => {
      this.entityFormService.getChildren(callback, this.config.initial)
      }
    }
  };


...snip..

```



getChildren is a service defined in a diffrent file, entity-form.service.ts

```


  getChildren(callback: Function, dir: string): void {
    this.ws.call('filesystem.listdir', [dir]).subscribe((res) => {
      let children = []
      for (let i = 0; i < res.length; i++) {
        let child = {};
        if (res[i].hasOwnProperty('name')) {
          child['value'] = res[i].name;
          // child['path'] = res[i].path;
          if(res[i].type === 'DIRECTORY') {
            child['loadChildren'] = (nextCallback) => this.getChildren(nextCallback, res[i].path);
          }
          children.push(child);
        }
      }
      callback(children);
    });
  }
```

by doing this I was hoping to call loadChildren everytime  I invoke the following, getChildren is never called (tested via adding debuggers in it)
```
<tree *ngIf="treeVisible" [tree]="tree" (nodeSelected)="onNodeSelected($event)" (nodeExpanded)="handleExpanded($event)">
```


but that's not the case please let us know what I am doing wrong

**Comment by Mariolocko** [comment]
@vaibhav-rbs 

Subscribe in the callback function:

`
loadChildren: (callback) => {
    this.ws.call('filesystem.listdir', [dir]).subscribe((res) => {
      let children = []
      for (let i = 0; i < res.length; i++) {
        let child = {};
        if (res[i].hasOwnProperty('name')) {
          child['value'] = res[i].name;
          // child['path'] = res[i].path;
          if(res[i].type === 'DIRECTORY') {
            child['loadChildren'] = (nextCallback) => this.getChildren(nextCallback, res[i].path);
          }
          children.push(child);
        }
      }
      callback(children);
    });
      }
`

**Comment by rychkog** [comment]
@vaibhav-rbs loadChildren designed to be called only once and only by clicking on the actual node.
And as far as I understand you are trying to push children to the node as in stream right?

**Comment by rychkog** [comment]
@vaibhav-rbs There is a new API that allows children reloading
https://github.com/valor-software/ng2-tree#gun-controller
