### ISSUE TITLE
I is not possible to load lazy node

### ISSUE THREAD

**Issue by logickphp** [valor-software/ng2-tree#75]
I am trying to load tree from http request from rest service when the user click the node.

` public tree: TreeModel = {
    value: 'Programming languages by programming paradigm',
    settings: {
      'static': true
    },
    children: [
      {
        value: 'Unidades',
        loadChildren: (callback) => {
          this.getUnidades(callback);
        }
      }
    ]
  };

 public getUnidades(callback) {
    this.dir3Service.unidades.subscribe(
      unidades=>{
        console.log(JSON.parse(unidades));
        callback(JSON.parse(unidades))
      },
      error=>console.error(`Error: ${error}`)
    );
  }
`
The response is:

`$raw_data = '[{
    "value": "Prototype-based programming",
    "children": [         
          {
            "value": "C++"
          },
          {
            "value": "C#",
            "loadChildren": "(callback) => {this.getUnidades(callback);}"            
          }
    ]
}]';`

The component do not evaluate "(callback) => {this.getUnidades(callback);}"          and it is not possible to load nodes recursive.

¿What it is the correct  process to load a external data?
Please work in a example.

Thank you !.

**Comment by rychkog** [comment]
@logickphp From what I see in 
`$raw_data = '[{ "value": "Prototype-based programming", "children": [ { "value": "C++" }, { "value": "C#", "loadChildren": "(callback) => {this.getUnidades(callback);}" } ] }]';`

`"(callback) => {this.getUnidades(callback);}" ` is a string and not a function, hence [this chunk of code](https://github.com/valor-software/ng2-tree/blob/master/src/tree.ts#L34) simply ignores it

**Comment by logickphp** [comment]
But there is no way to pass (callback) => {this.getUnidades(callback);} via json because I am obtain parse Json error when get response from rest service.

**Comment by rychkog** [comment]
@logickphp You should transform JSON received by you into proper TreeModel object with functions (if you need async loading) before feeding it to the tree

**Comment by logickphp** [comment]
The idea is calling rest service when the user click over one node because the tree will have about 300.000 nodes!!!!. It is not possible to load before. I have a first node and then I want to load after this each node. It is not possible evaluate typescript code in runtime in browser...

**Comment by rychkog** [comment]
@logickphp You have your `function that initiates data loading`. It requests just a tree with top level nodes. For the every top level node, you should add a loadChildren function. Then, on top level node expand, it requests its children via  `function that initiates data loading` and procedure repeats. Let's call it lazy recursion.

**Comment by logickphp** [comment]
Ok, I get it !

`
public tree: TreeModel = {
    value: 'Ámbitos',
    settings: {
      'static': true
    },
    children: [
      {
        value: 'Unidades',
        loadChildren: (callback) => {
          this.getUnidades(callback, null);
        }
      }
    ]
  };


public getUnidades(callback, unidad: string) {
this.dir3Service.getUnidades(codigo_unidad).subscribe(
      unidades => {

        for (let unidad of unidades) {
          x.push(
            {
              value: unidad['value'],
              loadChildren: (callback) => {
                this.getUnidades(callback, unidad['value']);
              }
            }
          )
        }

        callback(x);
      },
      error => console.error(`Error: ${error}`)
    );
`

Its working !!!!

**Comment by rychkog** [comment]
@logickphp I'm glad it's working :)

**Comment by logickphp** [comment]
Thank you so much.

**Comment by laoergege** [comment]
@rychkog  Thank you， Also solve my problem

**Comment by robinmaple** [comment]
This helped tremendously as well. Good to involve this sample in documentation as a reference.
