### ISSUE TITLE
Deprecated template warning when used in NG4

### ISSUE THREAD

**Issue by pdhar-tibco** [valor-software/ng2-tree#76]
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("node-menu *ngIf="isMenuVisible" (menuItemSelected)="onMenuItemSelected($event)"></node-menu>

      [WARNING ->]<template [ngIf]="tree.isNodeExpanded()">
        <tree-internal *ngFor="let child of tree.childrenAs"): ng:///TreeModule/TreeInternalComponent.html@25:6

**Comment by pdhar-tibco** [comment]
Is there a way to use or add custom icons with tree nodes and leaves ?
Also is there way to show tree lines and branches and selectable check boxes instead of expanding triangle nodes , similar to jsTree ?

**Comment by rychkog** [comment]
@pdhar-tibco 
> Is there a way to use or add custom icons with tree nodes and leaves ?

There is a PR for this - so this will be available in a future version.

> Also is there way to show tree lines and branches and selectable check boxes instead of expanding triangle nodes , similar to jsTree ?

No this is not available yet

**Comment by rychkog** [comment]
>The element is deprecated. Use instead ("node-menu *ngIf="isMenuVisible" (menuItemSelected)="onMenuItemSelected($event)">

Thanks for this!

**Comment by rychkog** [comment]
@pdhar-tibco Fixed
