### ISSUE TITLE
Load children asynchronously calls load children function more than once

### ISSUE THREAD

**Issue by lovery** [valor-software/ng2-tree#80]
I'm trying to use asynchronous loading of children and my server is called several times.
I've investigate and find out that `childrenAsync` in `Tree` class is called more than once.
In the demo example it's called twice. When I'm using it with a request to a server, it's called 4 or 6 times.

**Comment by rychkog** [comment]
@lovery Could you, please, give me a TreeModel that you are using (I need a structure - actual data can be faked)

**Comment by dekenless** [comment]
I too have witnessed this. I "resolved" this by wrapping my call to my service (which makes a WEBAPI call) with setTimeout (yes, this ugly and I would consider it a hack):

 ```
 public tree: TreeModel = {
        value: 'Root',
        loadChildren: (callback) => {            
            setTimeout(() => {
		        --getNode calls WEBAPI
                this.service.getRootNode(callback);
            }, 10);
        }
	};
```

**Comment by lovery** [comment]
@rychkog I've managed to create a demo of the problem. You can clone [this branch](https://github.com/IndustriaTech/ng2-tree/tree/loagin-children-server-side) and there is an example - Server tree at the bottom of the demo page.

**Comment by rychkog** [comment]
@lovery Great, thanks! Will be dealing with this today
