### ISSUE TITLE
Update for angular 2.4

### ISSUE THREAD

**Issue by logickphp** [valor-software/ng2-tree#83]
In angular >2.4:

core.es5.js:3033 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("node-menu *ngIf="isMenuVisible" (menuItemSelected)="onMenuItemSelected($event)"></node-menu>

      [WARNING ->]<template [ngIf]="tree.isNodeExpanded()">
        <tree-internal *ngFor="let child of tree.childrenAs"): ng:///TreeModule/TreeInternalComponent.html@25:6

**Comment by rychkog** [comment]
@logickphp, thanks! upcoming release will fix this

**Comment by rychkog** [comment]
@logickphp Done!
