### ISSUE TITLE
Can't bind to 'nodes' since it isn't a known property of 'tree-root' : Karma unit testing

### ISSUE THREAD

**Issue by MalliswariKulala** [valor-software/ng2-tree#84]
I am using angular-tree-component for my angular2 project. Facing 'Can't bind to 'nodes' since it isn't a known property of 'tree-root' error while running karma unit test cases.

import { TreeComponent, TREE_ACTIONS, KEYS, IActionMapping, TreeNode, TreeModel } from 'angular-tree-component';

I also have imported/added above line in my spec file

Could someone help?

**Comment by rychkog** [comment]
@MalliswariKulala What is `tree-root`? And `angular-tree-component` is not from this project
