### ISSUE TITLE
No Directive annotation found on TreeComponent

### ISSUE THREAD

**Issue by xcuben** [valor-software/ng2-tree#9]
Hi there,

by testing the treeComponent on my angular 2 app
and following the example-instructions
i had this Error : No Directive annotation found on TreeComponent

does anyone have any idea why/how to resolve such an issue ?

Thanks

**Comment by nick-wellinghoff-sp** [comment]
I get the same issue. This component is used in the ng2-admin theme and even in the theme it does not work on a fresh download.

**Comment by rychkog** [comment]
New version (1.0.0) is out. It is implemented on top of angular 2.2.4
