### ISSUE TITLE
Not able to expand or collapse nodes in ng2-tree

### ISSUE THREAD

**Issue by maverikarsh** [valor-software/ng2-tree#90]
I followed the instructions provided here https://www.npmjs.com/package/ng2-tree#eyes-demo for ng2-tree. However, I am not able to expand or collapse the tree nodes. There is no error displayed. I am using angular 4.0 . Am I missing something?

**Comment by rychkog** [comment]
@maverikarsh Have you included css styles?

**Comment by dgkTiqri** [comment]
I also have the same problem! i get the tree but cannot expand or collapse it.. 
Working with .net core + angular 2, Visual studio template , Web pack

Thanks in advance
