### ISSUE TITLE
[innerHTML] for node-value

### ISSUE THREAD

**Issue by dserresa** [valor-software/ng2-tree#94]
Tree model don't suport value/label model for items, only works with one. 
Currently, value shows with {{tree.value}} in tree-internal.component.js,  TreeInternalComponent.decorators.template. It's possible to show value with [innerHTML]="tree.value"?

This change help me to work with value/label model and i could do this at node list: 

```
children: [
        {
            value: '<label class="displayNone">myValue</label>myLabel',
            . . . 
        },
        . . . 
]
```

Thank you!

**Comment by rychkog** [comment]
@dserresa This is already done in latest development - will release in couple days

**Comment by dserresa** [comment]
When is the estimated release date?

Thanks!

**Comment by rychkog** [comment]
@dserresa in the latest version on npm this is already available
