### ISSUE TITLE
How To Feed TreeModel From a .json file via an HTTP.get Observable

### ISSUE THREAD

**Issue by rls1955** [valor-software/ng2-tree#95]
Great TreeModel interface. Never seen a tree with this level of capabilities!
Question: Have you or others been able to feed the TreeModel interface using an Angular2+ Observable HTTP.get on a .json file in place of the hard coded values? 

I am still getting aboard with Angular 2 and so far I have not been able to feed the "TreeModel" a sample set of data after "subscribing" to my mapped JSON data. I can display my retrieved "value" and "children" data using the template but can't figure out how to assign it to the TreeModel.
Here is a code snippet from the app.component.ts file:

=====================
.
.
.
    public trees: Array<TreeObject>;
  constructor(public treeService: TreeService) {
    // now it's a simple subscription to the observable
    treeService.getTrees()
      .subscribe(
       res => this.trees = res,
       error =>  this.errorMessage = <any>error);
  }     

       Below line is what I tried but did not work:
 // public fonts: TreeModel = { trees:Array(<TreeObject>) };
 // This did not work gave the below error which tells me I have issues with the "trees" JSON data :

========
 ERROR in ./demo/app.component.ts
(122,30): error TS2322: Type '{ trees: TreeObject[]; }' is not assignable to type 'TreeModel'.
  Object literal may only specify known properties, and 'trees' does not exist in type 'TreeModel'.
========

.
.
.
   Of course, below is the original code where the hard coded data is assigned to TreeModel:
.
.

public fonts: TreeModel = {
 value: 'Fonts',
    children: [
      {
        value: 'Serif  -  All my children and I are STATIC ¯\\_(ツ)_/¯',
        settings: {
.
.
.
This is not an issue per se but is something I thought would be of great benefit to users of the TreeModel.
Thanks,
Randy

**Comment by rychkog** [comment]
@rls1955 In order to use a tree you should feed it objects that conform to TreeModel interface
