### ISSUE TITLE
the way import lodash

### ISSUE THREAD

**Issue by dyh333** [valor-software/ng2-tree#97]
hi, @rychkog . I forked the 'chore-move-tree-to-new-angular-and-cli' branch. and found you import lodash like 
![image](https://cloud.githubusercontent.com/assets/1221313/26340949/d6f11f4a-3fc3-11e7-8910-5a11bc396157.png)

but when I import this branch into another repo, which import lodash also. and run start will report some error like 
![image](https://cloud.githubusercontent.com/assets/1221313/26340997/0a6f63ea-3fc4-11e7-805d-8dd7fd8cea3c.png)

so I wonder why you not import lodash as the simple way like 'import * as _ from 'lodash'?

**Comment by rychkog** [comment]
@dyh333 Hi! Here is why -
http://2ality.com/2015/12/webpack-tree-shaking.html
https://palantir.github.io/tslint/rules/import-blacklist/

These are the steps toward reducing ng2-tree module size

**Comment by rychkog** [comment]
ng2-tree has custom bundle procedure, so getting module via branch might not work
